-- Accessibility-specific instructions for active Firaxis tutorial advisor
-- messages and callout bodies. Gameplay explanations remain vanilla unless
-- their presentation depends on visual or pointer-based information.

-- Unit selection, movement, combat, and actions.
UPDATE LocalizedText SET Text = 'Use Vírgula ou Ponto para percorrer as unidades prontas para receber ordens até que o Colono seja selecionado.' WHERE Tag = 'LOC_META_1_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Com o Colono selecionado, pressione Tab para abrir a Lista de Ações da Unidade. Use as setas para cima e para baixo, ou digite parte de Fundar Cidade para encontrá-la, e então pressione Enter. Você também pode pressionar Alt mais B.' WHERE Tag = 'LOC_META_2_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Use Vírgula ou Ponto para percorrer as unidades prontas para receber ordens até que o Guerreiro seja selecionado.' WHERE Tag = 'LOC_META_9_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As unidades militares atacam unidades inimigas movendo-se para o hexágono delas. Com o Guerreiro selecionado, pressione Alt mais M e mova o cursor de navegação até o Guerreiro bárbaro. Pressione Espaço para ouvir a prévia de combate sem realizar o ataque. Ela anuncia o confronto e a avaliação, o dano previsto para os dois lados, as forças de combate e os modificadores. Pressione Enter uma vez para preparar o ataque e ouvir a prévia seguida de Pressione novamente para confirmar o combate. Pressione Enter de novo para atacar.' WHERE Tag = 'LOC_META_10_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As unidades Guerreiro têm um alcance de [ICON_Movement] Movimento de 2. Com o Guerreiro selecionado, pressione Shift mais 2 para ouvir seu movimento restante. Para um deslocamento imediato de um hexágono, use Alt mais Q ou Alt mais teclado numérico 7 para noroeste, Alt mais E ou Alt mais teclado numérico 9 para nordeste, Alt mais A ou Alt mais teclado numérico 4 para oeste, Alt mais D ou Alt mais teclado numérico 6 para leste, Alt mais Z ou Alt mais teclado numérico 1 para sudoeste, e Alt mais C ou Alt mais teclado numérico 3 para sudeste. Para um destino escolhido ou distante, pressione Alt mais M, mova o cursor de navegação, pressione Espaço para informações do destino, e então pressione Enter.' WHERE Tag = 'LOC_META_16_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Terrenos abertos, como Planície e Pradaria, consomem 1 ponto de [ICON_Movement] Movimento, enquanto Floresta, Colinas e outros terrenos difíceis consomem 2 ou mais. Mova o cursor de navegação até um hexágono e pressione X para ouvir seu custo de movimento e outras estatísticas físicas.' WHERE Tag = 'LOC_META_17_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Alt mais M, mova o cursor de navegação até o destino indicado e pressione Enter para mover seu Guerreiro. O Scanner do Mundo encontra objetos conhecidos do mapa sem verificar cada hexágono. Quando um marcador de mundo do tutorial aparece, seu hexágono é listado na categoria Tutorial. Use Ctrl mais Page Up e Ctrl mais Page Down para categorias, Shift mais Page Up e Shift mais Page Down para subcategorias, Page Up e Page Down para grupos, e Alt mais Page Up e Alt mais Page Down para itens. Pressione End para ouvir a direção e a distância até o resultado atual, ou Home para mover o cursor de navegação até lá.' WHERE Tag = 'LOC_META_17b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Para explorar uma Aldeia Tribal, mova uma de suas unidades para o hexágono dela. Com o Guerreiro selecionado, use o movimento rápido ou o modo de movimento para entrar no hexágono da Aldeia Tribal.' WHERE Tag = 'LOC_META_20_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'O Batedor tem um [ICON_Movement] Movimento de 3, permitindo que ele viaje mais longe do que muitas outras unidades. Com o Batedor selecionado, pressione Shift mais 2 para ouvir seu movimento restante, e então use o movimento rápido ou o modo de movimento para explorar em direção a terras não reveladas.' WHERE Tag = 'LOC_META_21_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Com o Construtor selecionado, use o movimento rápido ou o modo de movimento para alcançar o hexágono de Planície indicado ao lado da sua cidade.' WHERE Tag = 'LOC_META_23_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Com o Construtor selecionado neste hexágono, pressione Tab e abra o submenu de Melhorias. Esta é uma nova lista; use as setas para cima e para baixo ou digite parte de Fazenda para encontrar Construir Melhoria: Fazenda, e então pressione Enter.' WHERE Tag = 'LOC_META_24_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Os Construtores podem construir até 3 melhorias antes de esgotar sua mão de obra. Este Construtor usou uma carga e tem 2 restantes. Com o Construtor selecionado, pressione Shift mais 4 sempre que quiser ouvir suas cargas restantes.' WHERE Tag = 'LOC_META_26_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As unidades podem receber uma ordem de movimento de vários turnos, eliminando a necessidade de emitir uma ordem separada a cada turno. Selecione a unidade, pressione Alt mais M, mova o cursor de navegação até o destino final e pressione Enter.' WHERE Tag = 'LOC_META_28a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais S para mover o cursor de navegação até sua Capital atual, ou encontre-a na categoria Cidades do Scanner. Depois pressione Alt mais M, retorne o cursor à Capital se necessário, e pressione Enter para ordenar que o Guerreiro retorne para lá.' WHERE Tag = 'LOC_META_28_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Esta Pedra é um recurso bônus. Ela fornece +1 [ICON_Production] Produção adicional para sua cidade. Uma Pedreira aqui eleva esse bônus para +2 [ICON_Production] Produção. Mova o cursor de navegação até um hexágono e pressione W para ouvir seu recurso, rendimentos, trabalhador, água doce e informações de propriedade.' WHERE Tag = 'LOC_META_31a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Use o movimento rápido para mover o Construtor um hexágono para nordeste até o recurso Pedra. Uma vez lá, pressione Tab, abra o submenu de Melhorias, encontre Construir Melhoria: Pedreira e pressione Enter.' WHERE Tag = 'LOC_META_31b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Continue explorando com o Batedor usando o movimento rápido ou ordens de movimento de vários turnos.' WHERE Tag = 'LOC_META_35_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Com o Guerreiro selecionado, pressione Alt mais F. Você também pode pressionar Tab, encontrar Fortificar na Lista de Ações da Unidade e pressionar Enter.' WHERE Tag = 'LOC_META_36_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Quando não estiver avançando com uma unidade militar, muitas vezes é útil fortificá-la. Fortificar por até 2 turnos aumenta sua [ICON_Strength] Força de Combate quando ela é atacada. Fortificar está disponível na Lista de Ações da Unidade e também tem o atalho Alt mais F.' WHERE Tag = 'LOC_META_36a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Seu Construtor ainda tem uma carga restante. Pressione Shift mais 4 com ele selecionado para ouvir suas cargas. Você pode construir uma Mina na Colina para [ICON_Production] Produção ou uma Fazenda na Planície para [ICON_Food] Alimento. Mover e construir podem levar turnos separados.' WHERE Tag = 'LOC_META_38a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Uma maneira fácil de mover o Colono e o Guerreiro juntos é uni-los em uma formação de escolta. O comando de formação está na Lista de Ações da Unidade.' WHERE Tag = 'LOC_META_43a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Selecione o Colono ou o Guerreiro, pressione Tab, encontre Criar Formação de Escolta com a outra unidade e pressione Enter.' WHERE Tag = 'LOC_META_43_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Este destino está a vários hexágonos de distância. Selecione a formação, pressione Alt mais M, mova o cursor de navegação até o destino indicado a sudeste e pressione Enter para emitir uma ordem de movimento. Você pode usar o Batedor para exploração livre ao longo do caminho.' WHERE Tag = 'LOC_META_44_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Quando o Colono puder, use Fundar Cidade na Lista de Ações da Unidade ou pressione Alt mais B. Se ele não tiver [ICON_Movement] Movimento restante, encerre o turno primeiro.' WHERE Tag = 'LOC_META_57_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Cada [ICON_GreatPerson] Grande Personalidade pode ativar um ou mais bônus especiais em um local exigido do mapa. Quando a Grande Personalidade estiver no lugar correto, use Ativar Grande Personalidade na Lista de Ações da Unidade. Ela desaparece após usar todos os seus bônus.' WHERE Tag = 'LOC_META_138_BODY' AND Language = 'pt_BR';

-- Map exploration, plots, cities, and spoken information.
UPDATE LocalizedText SET Text = 'No início do jogo, sua cidade e as terras próximas estão reveladas, enquanto o resto do mundo está inexplorado. Mova o cursor de navegação com Q, E, A, D, Z e C, ou as direções correspondentes do teclado numérico. A fala do cursor identifica os hexágonos inexplorados.' WHERE Tag = 'LOC_META_14_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'O Guerreiro usou todo o seu [ICON_Movement] Movimento e terminou por este turno. Pressione Shift mais 2 com ele selecionado para ouvir que não resta movimento. A produção e a pesquisa ainda estão em andamento, então não há outras decisões a tomar.' WHERE Tag = 'LOC_META_19_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Os recursos são agrupados como recursos de luxo, estratégicos e bônus. Os recursos de luxo fornecem [ICON_Amenities] Serviços, os recursos estratégicos permitem unidades poderosas e os recursos bônus adicionam rendimentos. A categoria Recursos do Scanner encontra recursos conhecidos por essas classes e por tipo de recurso. Mova o cursor de navegação até um hexágono e pressione W para ouvir seu recurso e rendimentos.' WHERE Tag = 'LOC_META_30_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Ao escolher um local para uma cidade, considere o [ICON_Food] Alimento, os recursos e a água doce próximos. A categoria Recomendações do Scanner lista locais adequados para assentamento, mas o tutorial já escolheu um destino para você, como faz agora. Mova o cursor de navegação pelas terras ao redor e pressione W para ouvir rendimentos, recursos, trabalhadores, água doce e propriedade.' WHERE Tag = 'LOC_META_56_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'O tamanho de uma cidade é representado por sua [ICON_Citizen] População. Selecione a cidade e pressione Til para um resumo.' WHERE Tag = 'LOC_META_103_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Cada cidade reivindica as terras ao redor para seu controle exclusivo. Mova o cursor de navegação pelos hexágonos próximos e pressione W para ouvir a propriedade junto com os rendimentos e a água doce. As características e os recursos dentro de suas fronteiras influenciam fortemente a cidade.' WHERE Tag = 'LOC_META_104_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Cada cidade gera rendimentos a partir dos hexágonos que trabalha no início de cada turno. Selecione uma cidade e pressione Shift mais 7 para ouvir seus rendimentos totais. Mova o cursor de navegação até um hexágono individual e pressione W para ouvir os rendimentos e o trabalhador daquele hexágono.' WHERE Tag = 'LOC_META_106_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Cada hexágono dentro das fronteiras da sua cidade pode fornecer rendimentos. O [ICON_Food] Alimento impulsiona o crescimento da cidade, enquanto a [ICON_Production] Produção constrói unidades, edifícios, distritos e maravilhas. Selecione a cidade e pressione Shift mais 3 para o crescimento ou Shift mais 7 para os rendimentos totais.' WHERE Tag = 'LOC_META_107_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Um hexágono precisa ser trabalhado por um dos seus [ICON_Citizen] Cidadãos para fornecer seus rendimentos, e cada Cidadão pode trabalhar um hexágono. Coloque o cursor de navegação sobre um hexágono e pressione W para ouvir se ele está sendo trabalhado.' WHERE Tag = 'LOC_META_108_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Quando o posicionamento de distrito começa, a categoria Alvos válidos do Scanner lista os hexágonos de posicionamento disponíveis. Mova o cursor de navegação entre eles e pressione Espaço para as informações de posicionamento do hexágono atual e os detalhes de adjacência.' WHERE Tag = 'LOC_META_81_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Este hexágono tem Montanhas em duas bordas, fornecendo +2 [ICON_Science] Ciência por turno para um Campus aqui. No modo de posicionamento, pressione Espaço no cursor de navegação para ouvir as informações de posicionamento e adjacência do hexágono atual.' WHERE Tag = 'LOC_META_82_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Mova o cursor de navegação até o hexágono escolhido, pressione Espaço para revisar suas informações de posicionamento do Campus, e então pressione Enter para começar a construir o Campus.' WHERE Tag = 'LOC_META_83_BODY' AND Language = 'pt_BR';

-- Production and turn progression.
UPDATE LocalizedText SET Text = 'Com a cidade selecionada, pressione Tab para abrir a Lista de Ações da Cidade, encontre Alterar Produção e pressione Enter. Você também pode pressionar Alt mais Barra invertida.' WHERE Tag = 'LOC_META_3_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'O Seletor de Produção é uma árvore de unidades, edifícios, distritos e maravilhas. Use as setas para cima e para baixo para percorrer os itens visíveis e as setas para a esquerda e para a direita para recolher ou expandir categorias. Você também pode digitar parte do nome de um item para encontrá-lo. Pressione Enter no item que deseja produzir.' WHERE Tag = 'LOC_META_4a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Espaço para encerrar seu turno.' WHERE Tag = 'LOC_META_5_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Espaço para continuar para o próximo turno.' WHERE Tag = 'LOC_META_13_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Espaço mais uma vez para continuar para o próximo turno.' WHERE Tag = 'LOC_META_19b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Além de treinar unidades, uma cidade pode construir edifícios como o Monumento. Encontre Monumento na árvore de Produção e pressione Enter.' WHERE Tag = 'LOC_META_27_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Continue explorando com o Batedor. Quando terminar de dar ordens ao Construtor e ao Batedor, pressione Ctrl mais Espaço para encerrar o turno.' WHERE Tag = 'LOC_META_39_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Abra o Seletor de Produção a partir de Alterar Produção na Lista de Ações da Cidade, ou com Alt mais Barra invertida.' WHERE Tag = 'LOC_META_41b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Colono na árvore de Produção e pressione Enter para começar a treiná-lo.' WHERE Tag = 'LOC_META_41_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Lançador na árvore de Produção e pressione Enter. Quando a produção estiver escolhida, pressione Ctrl mais Espaço para encerrar o turno.' WHERE Tag = 'LOC_META_45_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Construir itens leva tempo. Cada item no Seletor de Produção anuncia seu custo e os turnos para concluir. A estimativa compara o custo de [ICON_Production] Produção do item com a [ICON_Production] Produção por turno da cidade. Com a cidade selecionada, pressione Shift mais 2 para ouvir sua produção atual e os turnos restantes.' WHERE Tag = 'LOC_META_5b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Campus na árvore de Produção e pressione Enter para começar a construir um nesta cidade.' WHERE Tag = 'LOC_META_80_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Abra Alterar Produção a partir da cidade selecionada com Alt mais Barra invertida ou pela Lista de Ações da Cidade. Encontre Biblioteca na árvore de Produção e pressione Enter.' WHERE Tag = 'LOC_META_87_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Para suspender uma tarefa de produção e treinar uma unidade de combate, abra Alterar Produção e escolha a unidade na árvore de Produção. O item anterior mantém seu progresso acumulado.' WHERE Tag = 'LOC_META_90_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Construtor na árvore de Produção e pressione Enter para começar a treiná-lo.' WHERE Tag = 'LOC_META_102_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Agora cabe a você escolher o que esta cidade produz. Opções úteis na árvore de Produção incluem um Construtor para melhorias, uma unidade de combate para seu exército, ou um Celeiro para [ICON_Food] Alimento e [ICON_Housing] Habitações.' WHERE Tag = 'LOC_META_110_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As tarefas que bloqueiam o fim do seu turno podem ser ouvidas com Shift mais Espaço. Pressione Ctrl mais Shift mais Espaço para abrir a lista completa de Bloqueadores de Turno. A produção terminou nesta cidade, então você precisa escolher o que ela produzirá em seguida.' WHERE Tag = 'LOC_META_11a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Escolher Produção é o único bloqueador de turno atual, então pressione Ctrl mais Espaço para abri-lo diretamente. Você também pode abrir a lista de Bloqueadores de Turno com Ctrl mais Shift mais Espaço, encontrar Escolher Produção e pressionar Enter.' WHERE Tag = 'LOC_META_11_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Um Construtor foi adicionado à Fila de Produção da cidade. Levará vários turnos para concluir. Sem decisões restantes, pressione Ctrl mais Espaço para encerrar o turno.' WHERE Tag = 'LOC_META_13a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A pesquisa de Cerâmica começou. Assim que mover o Batedor, pressione Ctrl mais Espaço para encerrar o turno.' WHERE Tag = 'LOC_META_117_BODY' AND Language = 'pt_BR';

-- Research, civics, government, and other screens.
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Espaço enquanto Escolher Pesquisa for a ação de turno atual para abrir o Seletor de Pesquisa. Você também pode pressionar Ctrl mais Shift mais Espaço para a lista de Bloqueadores de Turno, usar as setas para cima e para baixo ou digitar parte de Escolher Pesquisa para encontrar o bloqueador de pesquisa, e então pressionar Enter.' WHERE Tag = 'LOC_META_6_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'O Seletor de Pesquisa abre na árvore de Pesquisas Disponíveis. Use as setas para cima e para baixo, ou digite parte de Mineração para encontrá-la, e então pressione Enter para começar a pesquisá-la.' WHERE Tag = 'LOC_META_7_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Cerâmica na árvore de Pesquisas Disponíveis e pressione Enter.' WHERE Tag = 'LOC_META_33_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Sua civilização deve estar sempre pesquisando uma tecnologia. Mineração está concluída, então você precisa escolher a próxima tecnologia antes de encerrar o turno.' WHERE Tag = 'LOC_META_116_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Espaço enquanto Escolher Pesquisa for a ação de turno atual para abrir o Seletor de Pesquisa.' WHERE Tag = 'LOC_META_332_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Irrigação na árvore de Pesquisas Disponíveis e pressione Enter.' WHERE Tag = 'LOC_META_SELECT_IRRIGATION' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Escrita está concluída, então escolha outra tecnologia na árvore de Pesquisas Disponíveis. Domesticação de Animais e Trabalho em Bronze são escolhas úteis.' WHERE Tag = 'LOC_META_84_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As descobertas tecnológicas levam a novas tecnologias por meio de pré-requisitos. A Árvore de Tecnologias mostra esses caminhos e o que cada tecnologia desbloqueia, usando as mesmas visualizações de grade, árvore e gráfico apresentadas para os cívicos.' WHERE Tag = 'LOC_META_46_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Shift mais R para abrir a Árvore de Tecnologias.' WHERE Tag = 'LOC_META_46a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A Árvore de Tecnologias abre inicialmente na visualização em grade e depois lembra a última visualização selecionada. Na visualização em grade, as eras formam colunas, com os níveis de pesquisa dispostos da esquerda para a direita dentro de cada era. Use a mesma navegação por setas e por digitação apresentada na Árvore Cívica. O menu suspenso Visualização contém Grade, Gráfico e Árvore. Alt mais 1 seleciona Grade, Alt mais 2 seleciona Gráfico e Alt mais 3 seleciona Árvore. Na visualização em gráfico, Direita segue uma tecnologia que a tecnologia em foco desbloqueia, Esquerda segue um pré-requisito, e Cima ou Baixo alterna as alternativas da última conexão. O Leitor de Elemento em Foco permite ouvir informações detalhadas sobre o item em foco, uma seção por vez. Alt mais seta para cima e Alt mais seta para baixo vão para a seção anterior e a próxima e as leem, e Alt mais Home e Alt mais End saltam para a primeira e a última seção e as leem.' WHERE Tag = 'LOC_META_47_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As tecnologias concluídas são anunciadas como concluídas na Árvore de Tecnologias. Cerâmica agora está marcada como concluída.' WHERE Tag = 'LOC_META_48_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As tecnologias que podem ser pesquisadas agora são anunciadas como disponíveis na Árvore de Tecnologias.' WHERE Tag = 'LOC_META_49_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As tecnologias cujos pré-requisitos estão incompletos são anunciadas como bloqueadas. Use o Leitor de Elemento em Foco para ouvir seus requisitos e outros detalhes. Na visualização em árvore alternativa, você também pode expandir uma tecnologia com a seta para a direita para navegar por seus pré-requisitos, desbloqueios e tecnologias posteriores como ramos.' WHERE Tag = 'LOC_META_50_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Escrita na Árvore de Tecnologias e pressione Enter para começar a pesquisá-la.' WHERE Tag = 'LOC_META_51_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Escrita agora é anunciada como a pesquisa atual na Árvore de Tecnologias. Sua dica de ferramenta inclui o número de turnos necessários para concluí-la e seu progresso atual.' WHERE Tag = 'LOC_META_52_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A dica de ferramenta de uma tecnologia também lista as unidades, edifícios, maravilhas, habilidades e recursos que ela desbloqueia ou revela quando concluída.' WHERE Tag = 'LOC_META_53A_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Esc para fechar a Árvore de Tecnologias.' WHERE Tag = 'LOC_META_54a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Na lista de Panteões, use as setas para cima e para baixo, ou digite parte do nome de um Panteão para encontrá-lo. Pressione Enter na sua escolha, revise a caixa de diálogo de confirmação, e então pressione Enter em Confirmar Panteão.' WHERE Tag = 'LOC_META_129d' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais L para abrir a tela de Religião e suas opções de Panteão.' WHERE Tag = 'LOC_META_129b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione F3 para abrir a tela de [ICON_GreatPerson] Grandes Personalidades. Na árvore de Grandes Personalidades, use as setas ou digite parte do nome da pessoa para encontrar o candidato recrutável. Pressione Tab até que Recrutar esteja em foco, e então pressione Enter.' WHERE Tag = 'LOC_META_136b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A Classificação Mundial acompanha o status de cada condição de vitória.' WHERE Tag = 'LOC_META_119_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione F8 para abrir a Classificação Mundial.' WHERE Tag = 'LOC_META_119a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A Classificação Mundial abre na aba Geral. A visualização em tabela compara cada competidor entre os tipos de vitória disponíveis. Use Ctrl mais Tab e Ctrl mais Shift mais Tab para mudar de aba.' WHERE Tag = 'LOC_META_120_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As outras abas da Classificação Mundial fornecem detalhes de cada vitória. Alt mais 1 seleciona tabelas em toda a tela e Alt mais 2 seleciona árvores. Pressione Esc quando estiver pronto para continuar.' WHERE Tag = 'LOC_META_121_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Se precisar de mais informações sobre algo no tutorial, pressione F1 para abrir a Civilopédia. A seção Mod de Acessibilidade também documenta os controles do CAI, os comandos de jogo e a navegação de telas.' WHERE Tag = 'LOC_META_123_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Na tela de Governo, pressione Ctrl mais Tab para mudar para a aba Políticas.' WHERE Tag = 'LOC_META_95b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Na aba Políticas, use as setas para encontrar o espaço Militar vazio e pressione Enter. Na árvore do seletor de políticas, use as setas ou digite parte de Disciplina para encontrá-la, e então pressione Enter. Repita com o espaço Econômico vazio e Planejamento Urbano. Pressione Tab até que Confirmar Políticas esteja em foco, e então pressione Enter.' WHERE Tag = 'LOC_META_96_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais P para abrir a tela de Governo.' WHERE Tag = 'LOC_META_93b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Agora você precisa escolher um novo cívico. A próxima etapa abre a Árvore Cívica, onde os caminhos cívicos estão dispostos por era e nível de pesquisa.' WHERE Tag = 'LOC_META_99a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Ctrl mais Shift mais C para abrir a Árvore Cívica.' WHERE Tag = 'LOC_META_99b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A Árvore Cívica abre inicialmente na visualização em grade e depois lembra a última visualização selecionada. O menu suspenso Visualização contém Grade, Gráfico e Árvore; Alt mais 1, Alt mais 2 e Alt mais 3 os selecionam nessa ordem. Na visualização em grade, use as setas para cima e para baixo dentro de um nível e as setas para a esquerda e para a direita entre os níveis, ou digite parte do nome de um cívico para encontrá-lo. Artesanato é o próximo cívico deste tutorial.' WHERE Tag = 'LOC_META_100_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Encontre Artesanato na Árvore Cívica e pressione Enter.' WHERE Tag = 'LOC_META_100b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Pressione Esc para fechar a Árvore Cívica.' WHERE Tag = 'LOC_META_100c_BODY' AND Language = 'pt_BR';

-- Trade Route Chooser.
UPDATE LocalizedText SET Text = 'O Seletor de Rota Comercial apresenta as cidades alcançáveis em uma árvore de destinos. Use as setas para cima e para baixo para percorrer os destinos visíveis e as setas para a esquerda e para a direita para recolher ou expandir grupos. Você também pode digitar parte do nome de uma cidade para encontrá-la. Com um Comerciante selecionado, pressione Shift mais 6 para ouvir seu alcance de rota terrestre e marítima, ou Shift mais 8 para ouvir sua rota atual e os rendimentos, se houver. Um Posto Comercial pode estender rotas futuras para mais longe.' WHERE Tag = 'LOC_META_144_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Cada destino inclui sua distância e rendimentos. Encontre a cidade que deseja na árvore de destinos e pressione Enter.' WHERE Tag = 'LOC_META_145b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Revise a rota selecionada na caixa de diálogo de confirmação. Iniciar Rota é o botão padrão, então pressione Enter para começar a rota. Use a seta para a esquerda ou para a direita se precisar alternar entre Iniciar Rota e Cancelar.' WHERE Tag = 'LOC_META_145c_BODY' AND Language = 'pt_BR';

-- First-use information keys and later concept-specific guidance.
UPDATE LocalizedText SET Text = 'Assim como a construção de novas unidades é impulsionada pela [ICON_Production] Produção, a pesquisa de novas tecnologias é impulsionada pela [ICON_Science] Ciência. Pressione R para ouvir sua Ciência por turno e o progresso atual da pesquisa.' WHERE Tag = 'LOC_META_111_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Ao acumular [ICON_Culture] Cultura, você acabou de desbloquear Código de Leis, que contém seu primeiro governo: Chefatura. Pressione P para ouvir sua Cultura por turno e o progresso atual do cívico.' WHERE Tag = 'LOC_META_93a_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Você deve ter notado que suas cidades vêm gerando uma pequena quantidade de [ICON_Faith] Fé a cada turno.[NEWLINE][NEWLINE]A [ICON_Faith] Fé é obtida ao longo do tempo com certos edifícios, distritos e políticas. Pressione F para ouvir seu saldo de Fé e sua Fé por turno.' WHERE Tag = 'LOC_META_128_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Sua cidade concluiu a produção do edifício Monumento. Todos os edifícios contribuem para o desenvolvimento de uma cidade de maneiras específicas. O Monumento aumenta a [ICON_Culture] Cultura gerada pela cidade, estendendo sua influência sobre hexágonos adicionais. Mova o cursor de navegação até o hexágono da cidade para ouvir seus edifícios junto com o resumo do hexágono, ou pressione B ali para ler seus edifícios e outros detalhes geográficos.' WHERE Tag = 'LOC_META_40_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'A [ICON_Citizen] População da sua primeira cidade cresceu de 1 para 2. Enquanto uma cidade estiver bem alimentada e seu povo estiver feliz, ela continuará a crescer. Os [ICON_Citizen] Cidadãos da cidade trabalham os hexágonos e as melhorias ao redor, contribuindo para maiores rendimentos. Populações mais altas contribuem para uma pesquisa de [ICON_Science] Ciência mais rápida, uma [ICON_Production] Produção da cidade mais rápida e um crescimento [ICON_Culture] Cultural mais rápido. Com a cidade selecionada, pressione Shift mais 6 para ouvir sua população, habitações e edifícios.' WHERE Tag = 'LOC_META_125_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Lembre-se: os Construtores só podem construir melhorias dentro das fronteiras da sua cidade.[NEWLINE][NEWLINE]Ao gerar [ICON_Culture] Cultura, as fronteiras da sua cidade se expandirão, dando acesso a mais recursos. Com a cidade selecionada, pressione Shift mais 4 para ouvir o progresso de crescimento de suas fronteiras.' WHERE Tag = 'LOC_META_38b_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'As unidades a distância tendem a ter uma força de defesa menor do que as unidades corpo a corpo, então mantenha-as perto de unidades amigas de outros tipos para proteção. Com uma unidade selecionada, pressione Shift mais 6 para ouvir sua força de combate, força a distância ou de bombardeio, e alcance.' WHERE Tag = 'LOC_META_104_OTHER_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'O restante deste tutorial vai ajudá-lo a alcançar sua primeira Vitória por Dominação.[NEWLINE][NEWLINE]O objetivo de uma Vitória por Dominação é que sua civilização seja a última a ocupar sua própria cidade [ICON_Capital] Capital.[NEWLINE][NEWLINE]Neste tutorial, você deve capturar a [ICON_Capital] Capital do seu rival enquanto impede que ele tome a sua.[NEWLINE][NEWLINE]Três objetivos opcionais vão ajudá-lo a conseguir isso. Pressione Ctrl mais Shift mais T para abrir a lista de Objetivos do Tutorial. Os objetivos do tutorial também aparecem no painel de Notificações.' WHERE Tag = 'LOC_META_122_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Você pode dispensar uma [ICON_GreatPerson] Grande Personalidade que não quer. Outros jogadores podem então reivindicá-la, a decisão não pode ser revertida, e seus Pontos de [ICON_GreatPerson] Grande Personalidade são guardados para uma oportunidade futura. Coloque o foco na Grande Personalidade e pressione Delete para dispensá-la. Alternativamente, pressione Tab para navegar pelos botões de ação disponíveis e pela biografia dessa pessoa.' WHERE Tag = 'LOC_META_140_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'Sua civilização pode estabelecer um número limitado de [ICON_TradeRoute] Rotas Comerciais. Os distritos Centro Comercial e Porto podem aumentar essa capacidade. Pressione G para ouvir seu saldo e sua renda de Ouro junto com suas Rotas Comerciais ativas e a capacidade de rotas.' WHERE Tag = 'LOC_META_142_BODY' AND Language = 'pt_BR';
UPDATE LocalizedText SET Text = 'À medida que joga, pense em como lidar com seus vizinhos e observe-os com atenção para entender sua estratégia. Pressione F4 para abrir a lista de líderes que você conheceu, e então pressione Enter em um líder para abrir a tela de Diplomacia detalhada dele.' WHERE Tag = 'LOC_META_157_BODY' AND Language = 'pt_BR';
