-- Accessibility-specific instructions for active Firaxis tutorial advisor
-- messages and callout bodies. Gameplay explanations remain vanilla unless
-- their presentation depends on visual or pointer-based information.

-- Unit selection, movement, combat, and actions.
UPDATE LocalizedText SET Text = 'Usa Coma o Punto para recorrer las unidades preparadas para recibir órdenes hasta que el Colono esté seleccionado.' WHERE Tag = 'LOC_META_1_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Con el Colono seleccionado, pulsa Tab para abrir la lista de acciones de la unidad. Usa Arriba y Abajo, o escribe parte de Fundar ciudad para encontrarla, y luego pulsa Intro. También puedes pulsar Alt más B.' WHERE Tag = 'LOC_META_2_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Usa Coma o Punto para recorrer las unidades preparadas para recibir órdenes hasta que el Guerrero esté seleccionado.' WHERE Tag = 'LOC_META_9_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las unidades militares atacan a las unidades enemigas entrando en su casilla. Con el Guerrero seleccionado, pulsa Alt más M y mueve el cursor de navegación hasta el Guerrero bárbaro. Pulsa Espacio para oír la previsión del combate sin lanzar el ataque. Anuncia el enfrentamiento y su valoración, el daño previsto para ambos bandos, las fuerzas de combate y los modificadores. Pulsa Intro una vez para armar el ataque y oír la previsión seguida de Pulsa otra vez para confirmar el combate. Pulsa Intro de nuevo para atacar.' WHERE Tag = 'LOC_META_10_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las unidades de Guerrero tienen un alcance de Movimiento [ICON_Movement] de 2. Con el Guerrero seleccionado, pulsa Mayús más 2 para oír su movimiento restante. Para un movimiento inmediato de una casilla, usa Alt más Q o Alt más 7 del teclado numérico para el noroeste, Alt más E o Alt más 9 del teclado numérico para el noreste, Alt más A o Alt más 4 del teclado numérico para el oeste, Alt más D o Alt más 6 del teclado numérico para el este, Alt más Z o Alt más 1 del teclado numérico para el suroeste, y Alt más C o Alt más 3 del teclado numérico para el sureste. Para un destino elegido o lejano, pulsa Alt más M, mueve el cursor de navegación, pulsa Espacio para oír la información del destino y luego pulsa Intro.' WHERE Tag = 'LOC_META_16_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El terreno abierto, como las llanuras y las praderas, consume 1 punto de Movimiento [ICON_Movement], mientras que los bosques, las colinas y otros terrenos difíciles consumen 2 o más. Mueve el cursor de navegación a una casilla y pulsa X para oír su coste de movimiento y otras estadísticas físicas.' WHERE Tag = 'LOC_META_17_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Alt más M, mueve el cursor de navegación al destino indicado y pulsa Intro para mover a tu Guerrero. El escáner del mundo encuentra objetos conocidos del mapa sin revisar cada casilla. Cuando aparece un marcador del mundo del tutorial, su casilla se muestra en la categoría Tutorial. Usa Control más Re Pág y Control más Av Pág para las categorías, Mayús más Re Pág y Mayús más Av Pág para las subcategorías, Re Pág y Av Pág para los grupos, y Alt más Re Pág y Alt más Av Pág para los elementos. Pulsa Fin para oír la dirección y la distancia hasta el resultado actual, o Inicio para mover allí el cursor de navegación.' WHERE Tag = 'LOC_META_17b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Para explorar una aldea tribal, mueve una de tus unidades a su casilla. Con el Guerrero seleccionado, usa el movimiento rápido o el modo de movimiento para entrar en la casilla de la aldea tribal.' WHERE Tag = 'LOC_META_20_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El Batidor tiene un Movimiento [ICON_Movement] de 3, lo que le permite viajar más lejos que muchas otras unidades. Con el Batidor seleccionado, pulsa Mayús más 2 para oír su movimiento restante y luego usa el movimiento rápido o el modo de movimiento para explorar hacia tierras sin revelar.' WHERE Tag = 'LOC_META_21_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Con el Constructor seleccionado, usa el movimiento rápido o el modo de movimiento para llegar a la casilla de llanuras indicada junto a tu ciudad.' WHERE Tag = 'LOC_META_23_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Con el Constructor seleccionado en esta casilla, pulsa Tab y abre el submenú Mejoras. Es una lista nueva; usa Arriba y Abajo o escribe parte de Granja para encontrar Construir mejora: Granja, y luego pulsa Intro.' WHERE Tag = 'LOC_META_24_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Los Constructores pueden construir hasta 3 mejoras antes de agotar su mano de obra. Este Constructor ha usado una carga y le quedan 2. Con el Constructor seleccionado, pulsa Mayús más 4 siempre que quieras oír sus cargas restantes.' WHERE Tag = 'LOC_META_26_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Se puede dar a las unidades una orden de movimiento de varios turnos, lo que evita tener que dar una orden distinta cada turno. Selecciona la unidad, pulsa Alt más M, mueve el cursor de navegación hasta el destino final y pulsa Intro.' WHERE Tag = 'LOC_META_28a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más S para mover el cursor de navegación a tu capital actual, o encuéntrala en la categoría Ciudades del escáner. Luego pulsa Alt más M, devuelve el cursor a la capital si es necesario y pulsa Intro para ordenar al Guerrero que vuelva allí.' WHERE Tag = 'LOC_META_28_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Esta Piedra es un recurso de bonificación. Proporciona +1 adicional a la Producción [ICON_Production] de tu ciudad. Una Cantera aquí eleva esa bonificación a +2 de Producción [ICON_Production]. Mueve el cursor de navegación a una casilla y pulsa W para oír su recurso, sus rendimientos, su trabajador, el agua dulce y la propiedad.' WHERE Tag = 'LOC_META_31a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Usa el movimiento rápido para mover al Constructor una casilla al noreste, sobre el recurso de Piedra. Una vez allí, pulsa Tab, abre el submenú Mejoras, encuentra Construir mejora: Cantera y pulsa Intro.' WHERE Tag = 'LOC_META_31b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Sigue explorando con el Batidor mediante el movimiento rápido o las órdenes de movimiento de varios turnos.' WHERE Tag = 'LOC_META_35_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Con el Guerrero seleccionado, pulsa Alt más F. También puedes pulsar Tab, encontrar Fortificar en la lista de acciones de la unidad y pulsar Intro.' WHERE Tag = 'LOC_META_36_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cuando una unidad militar no está avanzando, suele ser útil fortificarla. Fortificarse durante un máximo de 2 turnos aumenta su Fuerza de combate [ICON_Strength] cuando la atacan. Fortificar está disponible en la lista de acciones de la unidad y también tiene el atajo Alt más F.' WHERE Tag = 'LOC_META_36a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'A tu Constructor todavía le queda una carga. Pulsa Mayús más 4 con él seleccionado para oír sus cargas. Puedes construir una Mina en la colina para obtener Producción [ICON_Production] o una Granja en las llanuras para obtener Alimentos [ICON_Food]. Moverse y construir pueden requerir turnos distintos.' WHERE Tag = 'LOC_META_38a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Una forma fácil de mover juntos al Colono y al Guerrero es unirlos en una formación de escolta. La orden de formación está en la lista de acciones de la unidad.' WHERE Tag = 'LOC_META_43a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Selecciona al Colono o al Guerrero, pulsa Tab, encuentra Crea formación de Escolta con la otra unidad y pulsa Intro.' WHERE Tag = 'LOC_META_43_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Este destino está a varias casillas. Selecciona la formación, pulsa Alt más M, mueve el cursor de navegación al destino indicado al sureste y pulsa Intro para dar la orden de movimiento. Puedes usar al Batidor para explorar libremente por el camino.' WHERE Tag = 'LOC_META_44_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cuando el Colono pueda, usa Fundar ciudad en la lista de acciones de la unidad o pulsa Alt más B. Si no le queda Movimiento [ICON_Movement], termina el turno primero.' WHERE Tag = 'LOC_META_57_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cada Gran personaje [ICON_GreatPerson] puede activar una o más bonificaciones especiales en una ubicación concreta del mapa. Cuando el gran personaje esté en el lugar correcto, usa Activar gran personaje en la lista de acciones de la unidad. Desaparece tras usar todas sus bonificaciones.' WHERE Tag = 'LOC_META_138_BODY' AND Language = 'es_ES';

-- Map exploration, plots, cities, and spoken information.
UPDATE LocalizedText SET Text = 'Al principio de la partida se revelan tu ciudad y las tierras cercanas, mientras que el resto del mundo está sin explorar. Mueve el cursor de navegación con Q, E, A, D, Z y C, o con las direcciones equivalentes del teclado numérico. La voz del cursor identifica las casillas sin explorar.' WHERE Tag = 'LOC_META_14_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El Guerrero ha usado todo su Movimiento [ICON_Movement] y ha terminado por este turno. Pulsa Mayús más 2 con él seleccionado para oír que no le queda movimiento. La producción y la investigación siguen en curso, así que no hay más decisiones que tomar.' WHERE Tag = 'LOC_META_19_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Los recursos se agrupan en recursos de lujo, estratégicos y de bonificación. Los recursos de lujo proporcionan Servicios [ICON_Amenities], los estratégicos permiten unidades poderosas y los de bonificación añaden rendimientos. La categoría Recursos del escáner encuentra los recursos conocidos por estas clases y por tipo de recurso. Mueve el cursor de navegación a una casilla y pulsa W para oír su recurso y sus rendimientos.' WHERE Tag = 'LOC_META_30_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Al elegir la ubicación de una ciudad, ten en cuenta los Alimentos [ICON_Food], los recursos y el agua dulce cercanos. La categoría Recomendaciones del escáner muestra ubicaciones adecuadas para asentarse, pero el tutorial ya ha elegido un destino por ti, como hace ahora. Mueve el cursor de navegación por las tierras circundantes y pulsa W para oír rendimientos, recursos, trabajadores, agua dulce y propiedad.' WHERE Tag = 'LOC_META_56_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El tamaño de una ciudad se representa con su Población [ICON_Citizen]. Selecciona la ciudad y pulsa Tilde para oír un resumen.' WHERE Tag = 'LOC_META_103_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cada ciudad reclama las tierras circundantes para tu control exclusivo. Mueve el cursor de navegación por las casillas cercanas y pulsa W para oír la propiedad junto con los rendimientos y el agua dulce. Los elementos del terreno y los recursos dentro de tus fronteras influyen mucho en la ciudad.' WHERE Tag = 'LOC_META_104_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cada ciudad genera rendimientos de las casillas que trabaja al principio de cada turno. Selecciona una ciudad y pulsa Mayús más 7 para oír sus rendimientos totales. Mueve el cursor de navegación a una casilla concreta y pulsa W para oír los rendimientos y el trabajador de esa casilla.' WHERE Tag = 'LOC_META_106_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cada casilla dentro de las fronteras de tu ciudad puede proporcionar rendimientos. Los Alimentos [ICON_Food] impulsan el crecimiento de la ciudad, mientras que la Producción [ICON_Production] construye unidades, edificios, distritos y maravillas. Selecciona la ciudad y pulsa Mayús más 3 para el crecimiento o Mayús más 7 para los rendimientos totales.' WHERE Tag = 'LOC_META_107_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Una casilla debe ser trabajada por uno de tus Ciudadanos [ICON_Citizen] para proporcionar sus rendimientos, y cada ciudadano puede trabajar una casilla. Pon el cursor de navegación en una casilla y pulsa W para oír si está trabajada.' WHERE Tag = 'LOC_META_108_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cuando empieza la colocación de un distrito, la categoría Objetivos válidos del escáner muestra las casillas de colocación disponibles. Mueve el cursor de navegación entre ellas y pulsa Espacio para oír la información de colocación y los detalles de adyacencia de la casilla actual.' WHERE Tag = 'LOC_META_81_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Esta casilla tiene montañas en dos lados, lo que proporciona +2 de Ciencia [ICON_Science] por turno a un Campus construido aquí. En el modo de colocación, pulsa Espacio en el cursor de navegación para oír la información de colocación y adyacencia de la casilla actual.' WHERE Tag = 'LOC_META_82_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Mueve el cursor de navegación a la casilla elegida, pulsa Espacio para repasar su información de colocación del Campus y luego pulsa Intro para empezar a construir el Campus.' WHERE Tag = 'LOC_META_83_BODY' AND Language = 'es_ES';

-- Production and turn progression.
UPDATE LocalizedText SET Text = 'Con la ciudad seleccionada, pulsa Tab para abrir la lista de acciones de la ciudad, encuentra Cambiar producción y pulsa Intro. También puedes pulsar Alt más Barra invertida.' WHERE Tag = 'LOC_META_3_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El selector de producción es un árbol de unidades, edificios, distritos y maravillas. Usa Arriba y Abajo para moverte por los elementos visibles e Izquierda y Derecha para contraer o expandir las categorías. También puedes escribir parte del nombre de un elemento para encontrarlo. Pulsa Intro en el elemento que quieras producir.' WHERE Tag = 'LOC_META_4a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más Espacio para terminar tu turno.' WHERE Tag = 'LOC_META_5_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más Espacio para continuar al turno siguiente.' WHERE Tag = 'LOC_META_13_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más Espacio una vez más para continuar al turno siguiente.' WHERE Tag = 'LOC_META_19b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Además de entrenar unidades, una ciudad puede construir edificios como el Monumento. Encuentra Monumento en el árbol de producción y pulsa Intro.' WHERE Tag = 'LOC_META_27_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Sigue explorando con el Batidor. Cuando hayas terminado de dar órdenes al Constructor y al Batidor, pulsa Control más Espacio para terminar el turno.' WHERE Tag = 'LOC_META_39_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Abre el selector de producción desde Cambiar producción en la lista de acciones de la ciudad, o con Alt más Barra invertida.' WHERE Tag = 'LOC_META_41b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Colono en el árbol de producción y pulsa Intro para empezar a entrenarlo.' WHERE Tag = 'LOC_META_41_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Hondero en el árbol de producción y pulsa Intro. Cuando hayas elegido la producción, pulsa Control más Espacio para terminar el turno.' WHERE Tag = 'LOC_META_45_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Construir cosas lleva tiempo. Cada elemento del selector de producción anuncia su coste y los turnos que tarda en completarse. La estimación compara el coste de Producción [ICON_Production] del elemento con la Producción [ICON_Production] por turno de la ciudad. Con la ciudad seleccionada, pulsa Mayús más 2 para oír su producción actual y los turnos restantes.' WHERE Tag = 'LOC_META_5b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Campus en el árbol de producción y pulsa Intro para empezar a construir uno en esta ciudad.' WHERE Tag = 'LOC_META_80_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Abre Cambiar producción desde la ciudad seleccionada con Alt más Barra invertida o la lista de acciones de la ciudad. Encuentra Biblioteca en el árbol de producción y pulsa Intro.' WHERE Tag = 'LOC_META_87_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Para suspender una tarea de producción y entrenar una unidad de combate, abre Cambiar producción y elige la unidad en el árbol de producción. El elemento anterior conserva el progreso acumulado.' WHERE Tag = 'LOC_META_90_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Constructor en el árbol de producción y pulsa Intro para empezar a entrenarlo.' WHERE Tag = 'LOC_META_102_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Ahora te toca a ti elegir lo que produce esta ciudad. Entre las opciones útiles del árbol de producción están un Constructor para las mejoras, una unidad de combate para tu ejército o un Granero para Alimentos [ICON_Food] y Alojamiento [ICON_Housing].' WHERE Tag = 'LOC_META_110_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Puedes oír las tareas que bloquean el final de tu turno con Mayús más Espacio. Pulsa Control más Mayús más Espacio para abrir la lista completa de acciones que bloquean el turno. La producción ha terminado en esta ciudad, así que debes elegir qué produce a continuación.' WHERE Tag = 'LOC_META_11a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Elegir producción es la única acción que bloquea el turno ahora, así que pulsa Control más Espacio para abrirla directamente. También puedes abrir la lista de acciones que bloquean el turno con Control más Mayús más Espacio, encontrar Elegir producción y pulsar Intro.' WHERE Tag = 'LOC_META_11_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Se ha añadido un Constructor a la cola de producción de la ciudad. Tardará varios turnos en completarse. Como no quedan decisiones, pulsa Control más Espacio para terminar el turno.' WHERE Tag = 'LOC_META_13a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Ha empezado la investigación de Alfarería. Cuando hayas movido al Batidor, pulsa Control más Espacio para terminar el turno.' WHERE Tag = 'LOC_META_117_BODY' AND Language = 'es_ES';

-- Research, civics, government, and other screens.
UPDATE LocalizedText SET Text = 'Pulsa Control más Espacio mientras Elegir investigación sea la acción de turno actual para abrir el selector de investigación. También puedes pulsar Control más Mayús más Espacio para la lista de acciones que bloquean el turno, usar Arriba y Abajo o escribir parte de Elegir investigación para encontrar el bloqueo de investigación, y luego pulsar Intro.' WHERE Tag = 'LOC_META_6_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El selector de investigación se abre en el árbol de investigaciones disponibles. Usa Arriba y Abajo, o escribe parte de Minería para encontrarla, y luego pulsa Intro para empezar a investigarla.' WHERE Tag = 'LOC_META_7_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Alfarería en el árbol de investigaciones disponibles y pulsa Intro.' WHERE Tag = 'LOC_META_33_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Tu civilización siempre debe estar investigando una tecnología. Minería está completada, así que debes elegir la siguiente tecnología antes de terminar el turno.' WHERE Tag = 'LOC_META_116_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más Espacio mientras Elegir investigación sea la acción de turno actual para abrir el selector de investigación.' WHERE Tag = 'LOC_META_332_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Riego en el árbol de investigaciones disponibles y pulsa Intro.' WHERE Tag = 'LOC_META_SELECT_IRRIGATION' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Escritura está completada, así que elige otra tecnología del árbol de investigaciones disponibles. Ganadería y Forja del bronce son dos opciones útiles.' WHERE Tag = 'LOC_META_84_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Los descubrimientos tecnológicos conducen a más tecnologías mediante requisitos. El árbol de tecnologías muestra esos caminos y lo que desbloquea cada tecnología, con las mismas vistas de cuadrícula, árbol y grafo presentadas para los principios.' WHERE Tag = 'LOC_META_46_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más Mayús más R para abrir el árbol de tecnologías.' WHERE Tag = 'LOC_META_46a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El árbol de tecnologías se abre inicialmente en vista de cuadrícula y después recuerda la última vista seleccionada. En la vista de cuadrícula, las eras forman columnas, con los niveles de investigación ordenados de izquierda a derecha dentro de cada era. Usa las mismas teclas de flechas y la misma búsqueda por escritura presentadas en el árbol de principios. El desplegable Vista contiene Cuadrícula, Grafo y Árbol. Alt más 1 selecciona Cuadrícula, Alt más 2 selecciona Grafo y Alt más 3 selecciona Árbol. En la vista de grafo, Derecha sigue una tecnología que la tecnología con el foco desbloquea, Izquierda sigue un requisito, y Arriba o Abajo recorren las alternativas de la última conexión. El lector del control con el foco te permite oír información detallada del elemento con el foco sección a sección. Alt más Arriba y Alt más Abajo van a la sección anterior y siguiente y las leen, y Alt más Inicio y Alt más Fin saltan a la primera y la última sección y las leen.' WHERE Tag = 'LOC_META_47_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las tecnologías completadas se anuncian como completadas en el árbol de tecnologías. Alfarería ahora aparece marcada como completada.' WHERE Tag = 'LOC_META_48_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las tecnologías que se pueden investigar ahora se anuncian como disponibles en el árbol de tecnologías.' WHERE Tag = 'LOC_META_49_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las tecnologías cuyos requisitos están incompletos se anuncian como bloqueadas. Usa el lector del control con el foco para oír sus requisitos y otros detalles. En la vista de árbol alternativa, también puedes expandir una tecnología con Derecha para explorar sus requisitos, sus desbloqueos y las tecnologías posteriores como ramas.' WHERE Tag = 'LOC_META_50_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Escritura en el árbol de tecnologías y pulsa Intro para empezar a investigarla.' WHERE Tag = 'LOC_META_51_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Escritura se anuncia ahora como la investigación actual en el árbol de tecnologías. Su descripción emergente incluye el número de turnos necesarios para terminarla y su progreso actual.' WHERE Tag = 'LOC_META_52_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'La descripción emergente de una tecnología también muestra las unidades, los edificios, las maravillas, las habilidades y los recursos que desbloquea o revela al completarse.' WHERE Tag = 'LOC_META_53A_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Escape para cerrar el árbol de tecnologías.' WHERE Tag = 'LOC_META_54a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'En la lista de panteones, usa Arriba y Abajo, o escribe parte del nombre de un panteón para encontrarlo. Pulsa Intro en tu elección, repasa el cuadro de confirmación y luego pulsa Intro en Confirmar panteón.' WHERE Tag = 'LOC_META_129d' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más L para abrir la pantalla de religión y sus opciones de panteón.' WHERE Tag = 'LOC_META_129b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa F3 para abrir la pantalla de Grandes personajes [ICON_GreatPerson]. En el árbol de grandes personajes, usa las teclas de flechas o escribe parte del nombre del personaje para encontrar al candidato reclutable. Pulsa Tab hasta que Reclutar tenga el foco y luego pulsa Intro.' WHERE Tag = 'LOC_META_136b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'La clasificación mundial muestra el estado de todas las condiciones de victoria.' WHERE Tag = 'LOC_META_119_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa F8 para abrir la clasificación mundial.' WHERE Tag = 'LOC_META_119a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'La clasificación mundial se abre en su pestaña General. La vista de tabla compara a todos los competidores en los tipos de victoria disponibles. Usa Control más Tab y Control más Mayús más Tab para cambiar de pestaña.' WHERE Tag = 'LOC_META_120_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las demás pestañas de la clasificación mundial dan detalles de cada victoria. Alt más 1 selecciona tablas en toda la pantalla y Alt más 2 selecciona árboles. Pulsa Escape cuando quieras continuar.' WHERE Tag = 'LOC_META_121_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Si necesitas más información sobre algo del tutorial, pulsa F1 para abrir la Civilopedia. La sección del mod de accesibilidad también documenta los controles de CAI, las órdenes de juego y la navegación por las pantallas.' WHERE Tag = 'LOC_META_123_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'En la pantalla de gobierno, pulsa Control más Tab para cambiar a la pestaña Políticas.' WHERE Tag = 'LOC_META_95b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'En la pestaña Políticas, usa las teclas de flechas para encontrar la ranura militar vacía y pulsa Intro. En el árbol de selección de políticas, usa las teclas de flechas o escribe parte de Disciplina para encontrarla, y luego pulsa Intro. Repite con la ranura económica vacía y Planificación urbanística. Pulsa Tab hasta que Confirmar políticas tenga el foco y luego pulsa Intro.' WHERE Tag = 'LOC_META_96_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más P para abrir la pantalla de gobierno.' WHERE Tag = 'LOC_META_93b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Ahora tienes que elegir un nuevo principio. El siguiente paso abre el árbol de principios, donde los caminos de principios se organizan por era y nivel de investigación.' WHERE Tag = 'LOC_META_99a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Control más Mayús más C para abrir el árbol de principios.' WHERE Tag = 'LOC_META_99b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El árbol de principios se abre inicialmente en vista de cuadrícula y después recuerda la última vista seleccionada. El desplegable Vista contiene Cuadrícula, Grafo y Árbol; Alt más 1, Alt más 2 y Alt más 3 los seleccionan en ese orden. En la vista de cuadrícula, usa Arriba y Abajo dentro de un nivel e Izquierda y Derecha entre niveles, o escribe parte del nombre de un principio para encontrarlo. Artesanía es el siguiente principio de este tutorial.' WHERE Tag = 'LOC_META_100_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Encuentra Artesanía en el árbol de principios y pulsa Intro.' WHERE Tag = 'LOC_META_100b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Pulsa Escape para cerrar el árbol de principios.' WHERE Tag = 'LOC_META_100c_BODY' AND Language = 'es_ES';

-- Trade Route Chooser.
UPDATE LocalizedText SET Text = 'El selector de rutas comerciales presenta las ciudades alcanzables en un árbol de destinos. Usa Arriba y Abajo para moverte por los destinos visibles e Izquierda y Derecha para contraer o expandir los grupos. También puedes escribir parte del nombre de una ciudad para encontrarla. Con un Comerciante seleccionado, pulsa Mayús más 6 para oír su alcance de rutas terrestres y marítimas, o Mayús más 8 para oír su ruta actual y sus rendimientos si tiene una. Un puesto comercial puede ampliar el alcance de rutas posteriores.' WHERE Tag = 'LOC_META_144_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Cada destino incluye su distancia y sus rendimientos. Encuentra la ciudad que quieras en el árbol de destinos y pulsa Intro.' WHERE Tag = 'LOC_META_145b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Repasa la ruta seleccionada en el cuadro de confirmación. Iniciar ruta es el botón predeterminado, así que pulsa Intro para empezar la ruta. Usa Izquierda o Derecha si necesitas moverte entre Iniciar ruta y Cancelar.' WHERE Tag = 'LOC_META_145c_BODY' AND Language = 'es_ES';

-- First-use information keys and later concept-specific guidance.
UPDATE LocalizedText SET Text = 'Igual que la construcción de nuevas unidades se impulsa con Producción [ICON_Production], la investigación de nuevas tecnologías se impulsa con Ciencia [ICON_Science]. Pulsa R para oír tu Ciencia por turno y el progreso de la investigación actual.' WHERE Tag = 'LOC_META_111_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Al acumular Cultura [ICON_Culture], acabas de desbloquear Código de leyes, que contiene tu primer gobierno: Caciquismo. Pulsa P para oír tu Cultura por turno y el progreso del principio actual.' WHERE Tag = 'LOC_META_93a_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Puede que hayas notado que tus ciudades han estado generando una pequeña cantidad de Fe [ICON_Faith] cada turno.[NEWLINE][NEWLINE]La Fe [ICON_Faith] se gana con el tiempo gracias a ciertos edificios, distritos y políticas. Pulsa F para oír tu saldo de Fe y tu Fe por turno.' WHERE Tag = 'LOC_META_128_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Tu ciudad ha terminado la producción del edificio Monumento. Todos los edificios contribuyen al desarrollo de una ciudad de formas concretas. El Monumento aumenta la Cultura [ICON_Culture] que genera la ciudad, extendiendo su influencia a más hexágonos. Mueve el cursor de navegación a la casilla de la ciudad para oír sus edificios con el resumen de la casilla, o pulsa B allí para leer sus edificios y otros detalles geográficos.' WHERE Tag = 'LOC_META_40_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'La Población [ICON_Citizen] de tu primera ciudad ha crecido de 1 a 2. Mientras una ciudad esté bien alimentada y su gente sea feliz, seguirá creciendo. Los Ciudadanos [ICON_Citizen] de la ciudad trabajan las casillas y mejoras circundantes, contribuyendo a mayores rendimientos. Una Población [ICON_Citizen] más alta contribuye a investigar Ciencia [ICON_Science] más rápido, a una Producción [ICON_Production] urbana más rápida y a un crecimiento Cultural [ICON_Culture] más rápido. Con la ciudad seleccionada, pulsa Mayús más 6 para oír su población, su alojamiento y sus edificios.' WHERE Tag = 'LOC_META_125_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Recuerda: los Constructores solo pueden construir mejoras dentro de las fronteras de tu ciudad.[NEWLINE][NEWLINE]Al generar Cultura [ICON_Culture], las fronteras de tu ciudad se expandirán, dándote acceso a más recursos. Con la ciudad seleccionada, pulsa Mayús más 4 para oír el progreso de expansión de sus fronteras.' WHERE Tag = 'LOC_META_38b_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Las unidades a distancia suelen tener menos fuerza de defensa que las unidades cuerpo a cuerpo, así que mantenlas cerca de unidades aliadas de otros tipos para protegerlas. Con una unidad seleccionada, pulsa Mayús más 6 para oír su fuerza de combate, su fuerza a distancia o de bombardeo y su alcance.' WHERE Tag = 'LOC_META_104_OTHER_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'El resto de este tutorial te ayudará a lograr tu primera victoria por dominación.[NEWLINE][NEWLINE]El objetivo de una victoria por dominación es que tu civilización sea la última que ocupe su propia Capital [ICON_Capital].[NEWLINE][NEWLINE]En este tutorial, debes capturar la Capital [ICON_Capital] de tu rival mientras evitas que tomen la tuya.[NEWLINE][NEWLINE]Tres objetivos opcionales te ayudarán a lograrlo. Pulsa Control más Mayús más T para abrir la lista de objetivos del tutorial. Los objetivos del tutorial también aparecen en el panel de notificaciones.' WHERE Tag = 'LOC_META_122_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Puedes dejar pasar a un Gran personaje [ICON_GreatPerson] que no quieras. Otros jugadores podrán reclutarlo, la decisión no se puede deshacer y tus puntos de Gran personaje [ICON_GreatPerson] se guardan para una oportunidad futura. Pon el foco en el gran personaje y pulsa Suprimir para dejarlo pasar. También puedes pulsar Tab para explorar los botones de acción disponibles y la biografía de ese personaje.' WHERE Tag = 'LOC_META_140_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Tu civilización puede establecer un número limitado de Rutas comerciales [ICON_TradeRoute]. Los distritos de Centro comercial y Puerto pueden aumentar esta capacidad. Pulsa G para oír tu saldo y tus ingresos de oro junto con tus rutas comerciales activas y tu capacidad de rutas.' WHERE Tag = 'LOC_META_142_BODY' AND Language = 'es_ES';
UPDATE LocalizedText SET Text = 'Mientras juegas, piensa en cómo tratar a tus vecinos y obsérvalos con atención para entender su estrategia. Pulsa F4 para abrir la lista de líderes que has conocido y luego pulsa Intro en un líder para abrir su pantalla de diplomacia detallada.' WHERE Tag = 'LOC_META_157_BODY' AND Language = 'es_ES';
