-- Instrukcje dla ułatwień dostępu do aktywnych komunikatów doradcy samouczka
-- Firaxis oraz treści dymków. Objaśnienia mechaniki pozostają jak w oryginale,
-- chyba że ich prezentacja zależy od informacji wizualnych lub wskaźnika.

-- Wybór jednostki, ruch, walka i akcje.
UPDATE LocalizedText SET Text = 'Użyj Przecinka lub Kropki, aby przełączać jednostki gotowe do wydania rozkazów, aż zaznaczysz Osadnika.' WHERE Tag = 'LOC_META_1_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gdy Osadnik jest zaznaczony, naciśnij Tab, aby otworzyć Listę akcji jednostki. Użyj strzałek w górę i w dół albo wpisz fragment nazwy Załóż miasto, aby ją znaleźć, a następnie naciśnij Enter. Możesz też nacisnąć Alt plus B.' WHERE Tag = 'LOC_META_2_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Użyj Przecinka lub Kropki, aby przełączać jednostki gotowe do wydania rozkazów, aż zaznaczysz Wojownika.' WHERE Tag = 'LOC_META_9_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Jednostki wojskowe atakują wrogów, wchodząc na ich pole. Gdy Wojownik jest zaznaczony, naciśnij Alt plus M i przesuń kursor nawigacji na Wojownika barbarzyńców. Naciśnij Spację, aby usłyszeć podgląd walki bez rozpoczynania ataku. Odczytuje on zestawienie i ocenę starcia, przewidywane obrażenia obu stron, siły bojowe oraz modyfikatory. Naciśnij Enter raz, aby przygotować atak i usłyszeć podgląd zakończony słowami Naciśnij ponownie, aby potwierdzić walkę. Naciśnij Enter ponownie, aby zaatakować.' WHERE Tag = 'LOC_META_10_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Wojownicy mają zasięg [ICON_Movement] Ruchu wynoszący 2. Gdy Wojownik jest zaznaczony, naciśnij Shift plus 2, aby usłyszeć jego pozostały ruch. Aby od razu wykonać ruch o jedno pole, użyj Alt plus Q lub Alt plus Numpad 7 na północny zachód, Alt plus E lub Alt plus Numpad 9 na północny wschód, Alt plus A lub Alt plus Numpad 4 na zachód, Alt plus D lub Alt plus Numpad 6 na wschód, Alt plus Z lub Alt plus Numpad 1 na południowy zachód oraz Alt plus C lub Alt plus Numpad 3 na południowy wschód. Aby dotrzeć do wybranego lub odległego celu, naciśnij Alt plus M, przesuń kursor nawigacji, naciśnij Spację, aby usłyszeć informacje o celu, a następnie naciśnij Enter.' WHERE Tag = 'LOC_META_16_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Otwarty teren, taki jak Równiny i Łąki, kosztuje 1 punkt [ICON_Movement] Ruchu, natomiast Las, Wzgórza i inny trudny teren pochłaniają 2 lub więcej. Przesuń kursor nawigacji na pole i naciśnij X, aby usłyszeć jego koszt ruchu oraz inne właściwości fizyczne.' WHERE Tag = 'LOC_META_17_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Alt plus M, przesuń kursor nawigacji do wskazanego celu i naciśnij Enter, aby przemieścić Wojownika. Skaner świata odnajduje znane obiekty na mapie bez sprawdzania każdego pola. Gdy pojawi się znacznik świata samouczka, jego pole jest wymienione w kategorii Samouczek. Użyj Ctrl plus Page Up i Ctrl plus Page Down do kategorii, Shift plus Page Up i Shift plus Page Down do podkategorii, Page Up i Page Down do grup oraz Alt plus Page Up i Alt plus Page Down do elementów. Naciśnij End, aby usłyszeć kierunek i odległość do bieżącego wyniku, lub Home, aby przenieść tam kursor nawigacji.' WHERE Tag = 'LOC_META_17b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Aby zbadać Wioskę plemienną, wprowadź jedną ze swoich jednostek na jej pole. Gdy Wojownik jest zaznaczony, użyj szybkiego ruchu lub trybu ruchu, aby wejść na pole Wioski plemiennej.' WHERE Tag = 'LOC_META_20_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Zwiadowca ma [ICON_Movement] Ruch równy 3, dzięki czemu może podróżować dalej niż wiele innych jednostek. Gdy Zwiadowca jest zaznaczony, naciśnij Shift plus 2, aby usłyszeć jego pozostały ruch, a następnie użyj szybkiego ruchu lub trybu ruchu, aby badać nieodkryte ziemie.' WHERE Tag = 'LOC_META_21_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gdy Budowniczy jest zaznaczony, użyj szybkiego ruchu lub trybu ruchu, aby dotrzeć na wskazane pole Równin obok twojego miasta.' WHERE Tag = 'LOC_META_23_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gdy Budowniczy jest zaznaczony na tym polu, naciśnij Tab i otwórz podmenu Ulepszenia. To nowa lista; użyj strzałek w górę i w dół albo wpisz fragment nazwy Farma, aby znaleźć Zbuduj ulepszenie: Farma, a następnie naciśnij Enter.' WHERE Tag = 'LOC_META_24_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Budowniczowie mogą zbudować do 3 ulepszeń, zanim wyczerpią swoją siłę roboczą. Ten Budowniczy zużył jeden ładunek, a 2 mu pozostały. Gdy Budowniczy jest zaznaczony, naciśnij Shift plus 4, kiedy chcesz usłyszeć jego pozostałe ładunki.' WHERE Tag = 'LOC_META_26_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Jednostkom można wydać rozkaz ruchu na wiele tur, dzięki czemu nie trzeba go powtarzać w każdej turze. Zaznacz jednostkę, naciśnij Alt plus M, przesuń kursor nawigacji do miejsca docelowego i naciśnij Enter.' WHERE Tag = 'LOC_META_28a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus S, aby przenieść kursor nawigacji do twojej obecnej Stolicy, lub znajdź ją w kategorii Miasta Skanera. Następnie naciśnij Alt plus M, w razie potrzeby przywróć kursor na Stolicę i naciśnij Enter, aby rozkazać Wojownikowi tam wrócić.' WHERE Tag = 'LOC_META_28_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Ten Kamień to surowiec dodatkowy. Zapewnia twojemu miastu dodatkowe +1 [ICON_Production] Produkcji. Kamieniołom w tym miejscu zwiększa ten bonus do +2 [ICON_Production] Produkcji. Przesuń kursor nawigacji na pole i naciśnij W, aby usłyszeć informacje o jego surowcu, plonach, pracowniku, świeżej wodzie i przynależności.' WHERE Tag = 'LOC_META_31a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Użyj szybkiego ruchu, aby przesunąć Budowniczego o jedno pole na północny wschód, na surowiec Kamień. Gdy tam dotrze, naciśnij Tab, otwórz podmenu Ulepszenia, znajdź Zbuduj ulepszenie: Kamieniołom i naciśnij Enter.' WHERE Tag = 'LOC_META_31b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Kontynuuj eksplorację Zwiadowcą, korzystając z szybkiego ruchu lub rozkazów ruchu na wiele tur.' WHERE Tag = 'LOC_META_35_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gdy Wojownik jest zaznaczony, naciśnij Alt plus F. Możesz też nacisnąć Tab, znaleźć Fortyfikacja na Liście akcji jednostki i nacisnąć Enter.' WHERE Tag = 'LOC_META_36_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Kiedy jednostka wojskowa nie naciera, często warto ją ufortyfikować. Fortyfikacja przez maksymalnie 2 tury zwiększa jej [ICON_Strength] Siłę bojową podczas ataku. Fortyfikacja jest dostępna na Liście akcji jednostki i ma również skrót Alt plus F.' WHERE Tag = 'LOC_META_36a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Twój Budowniczy ma jeszcze jeden ładunek. Naciśnij Shift plus 4, gdy jest zaznaczony, aby usłyszeć jego ładunki. Możesz zbudować Kopalnię na Wzgórzu dla [ICON_Production] Produkcji albo Farmę na Równinach dla [ICON_Food] Żywności. Przemieszczenie i budowa mogą zająć osobne tury.' WHERE Tag = 'LOC_META_38a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Łatwym sposobem na wspólne przemieszczanie Osadnika i Wojownika jest połączenie ich w formację eskortową. Rozkaz formacji znajduje się na Liście akcji jednostki.' WHERE Tag = 'LOC_META_43a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Zaznacz Osadnika lub Wojownika, naciśnij Tab, znajdź Utwórz formację eskortową z drugą jednostką i naciśnij Enter.' WHERE Tag = 'LOC_META_43_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Ten cel jest oddalony o kilka pól. Zaznacz formację, naciśnij Alt plus M, przesuń kursor nawigacji do wskazanego celu na południowym wschodzie i naciśnij Enter, aby wydać rozkaz ruchu. Zwiadowcą możesz swobodnie eksplorować teren wzdłuż trasy.' WHERE Tag = 'LOC_META_44_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gdy Osadnik będzie mógł, użyj Załóż miasto na Liście akcji jednostki lub naciśnij Alt plus B. Jeśli nie ma już [ICON_Movement] Ruchu, najpierw zakończ turę.' WHERE Tag = 'LOC_META_57_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Każdy [ICON_GreatPerson] Wielki człowiek może aktywować jeden lub więcej specjalnych bonusów w wymaganym miejscu na mapie. Gdy Wielki człowiek znajdzie się we właściwym miejscu, użyj Aktywuj wielkiego człowieka na Liście akcji jednostki. Znika on po wykorzystaniu wszystkich swoich bonusów.' WHERE Tag = 'LOC_META_138_BODY' AND Language = 'pl_PL';

-- Eksploracja mapy, pola, miasta i informacje głosowe.
UPDATE LocalizedText SET Text = 'Na początku gry twoje miasto i pobliskie ziemie są odkryte, a reszta świata pozostaje niezbadana. Przesuwaj kursor nawigacji klawiszami Q, E, A, D, Z i C lub odpowiadającymi im kierunkami na klawiaturze numerycznej. Mowa kursora rozpoznaje niezbadane pola.' WHERE Tag = 'LOC_META_14_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Wojownik zużył cały swój [ICON_Movement] Ruch i zakończył działania w tej turze. Naciśnij Shift plus 2, gdy jest zaznaczony, aby usłyszeć, że nie został mu żaden ruch. Produkcja i badania wciąż trwają, więc nie ma innych decyzji do podjęcia.' WHERE Tag = 'LOC_META_19_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Surowce dzielą się na luksusowe, strategiczne i dodatkowe. Surowce luksusowe zapewniają [ICON_Amenities] Udogodnienia, surowce strategiczne umożliwiają tworzenie potężnych jednostek, a surowce dodatkowe zwiększają plony. Kategoria Surowce Skanera odnajduje znane surowce według tych klas oraz według rodzaju surowca. Przesuń kursor nawigacji na pole i naciśnij W, aby usłyszeć jego surowiec i plony.' WHERE Tag = 'LOC_META_30_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Wybierając miejsce na miasto, weź pod uwagę pobliską [ICON_Food] Żywność, surowce i świeżą wodę. Kategoria Rekomendacje Skanera wymienia odpowiednie miejsca na osadę, lecz samouczek już wybrał dla ciebie cel, tak jak teraz. Przesuwaj kursor nawigacji po okolicznych ziemiach i naciskaj W, aby poznać plony, surowce, pracowników, świeżą wodę i przynależność.' WHERE Tag = 'LOC_META_56_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Wielkość miasta odzwierciedla jego [ICON_Citizen] Populacja. Zaznacz miasto i naciśnij Tyldę, aby usłyszeć podsumowanie.' WHERE Tag = 'LOC_META_103_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Każde miasto zagarnia okoliczne ziemie pod twoją wyłączną kontrolę. Przesuwaj kursor nawigacji po pobliskich polach i naciskaj W, aby usłyszeć przynależność wraz z plonami i świeżą wodą. Cechy terenu i surowce w obrębie twoich granic mają duży wpływ na miasto.' WHERE Tag = 'LOC_META_104_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Każde miasto na początku każdej tury wytwarza plony z pól, które obrabia. Zaznacz miasto i naciśnij Shift plus 7, aby usłyszeć jego łączne plony. Przesuń kursor nawigacji na pojedyncze pole i naciśnij W, aby usłyszeć plony tego pola oraz jego pracownika.' WHERE Tag = 'LOC_META_106_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Każde pole w granicach twojego miasta może dawać plony. [ICON_Food] Żywność napędza rozwój miasta, a [ICON_Production] Produkcja pozwala tworzyć jednostki, budowle, dzielnice i cuda. Zaznacz miasto i naciśnij Shift plus 3, aby usłyszeć rozwój, lub Shift plus 7, aby usłyszeć łączne plony.' WHERE Tag = 'LOC_META_107_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Pole musi być obrabiane przez jednego z twoich [ICON_Citizen] Obywateli, aby dawało plony, a każdy Obywatel może obrabiać jedno pole. Ustaw kursor nawigacji na polu i naciśnij W, aby usłyszeć, czy jest obrabiane.' WHERE Tag = 'LOC_META_108_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gdy rozpocznie się rozmieszczanie dzielnicy, kategoria Prawidłowe cele Skanera wymienia dostępne pola do rozmieszczenia. Przesuwaj między nimi kursor nawigacji i naciskaj Spację, aby poznać informacje o rozmieszczeniu bieżącego pola oraz szczegóły sąsiedztwa.' WHERE Tag = 'LOC_META_81_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'To pole sąsiaduje z Górami na dwóch krawędziach, co zapewnia Kampusowi w tym miejscu +2 [ICON_Science] Nauki na turę. W trybie rozmieszczania naciśnij Spację przy kursorze nawigacji, aby usłyszeć informacje o rozmieszczeniu i sąsiedztwie bieżącego pola.' WHERE Tag = 'LOC_META_82_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Przesuń kursor nawigacji na wybrane pole, naciśnij Spację, aby sprawdzić informacje o rozmieszczeniu Kampusu, a następnie naciśnij Enter, aby rozpocząć jego budowę.' WHERE Tag = 'LOC_META_83_BODY' AND Language = 'pl_PL';

-- Produkcja i przebieg tury.
UPDATE LocalizedText SET Text = 'Gdy miasto jest zaznaczone, naciśnij Tab, aby otworzyć Listę akcji miasta, znajdź Zmień produkcję i naciśnij Enter. Możesz też nacisnąć Alt plus Ukośnik wsteczny.' WHERE Tag = 'LOC_META_3_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Okno wyboru produkcji to drzewo jednostek, budowli, dzielnic i cudów. Użyj strzałek w górę i w dół, aby poruszać się po widocznych pozycjach, oraz strzałek w lewo i w prawo, aby zwijać i rozwijać kategorie. Możesz też wpisać fragment nazwy pozycji, aby ją znaleźć. Naciśnij Enter na pozycji, którą chcesz produkować.' WHERE Tag = 'LOC_META_4a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Spacja, aby zakończyć turę.' WHERE Tag = 'LOC_META_5_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Spacja, aby przejść do następnej tury.' WHERE Tag = 'LOC_META_13_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Spacja jeszcze raz, aby przejść do następnej tury.' WHERE Tag = 'LOC_META_19b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Poza szkoleniem jednostek miasto może wznosić budowle, takie jak Pomnik. Znajdź Pomnik w drzewie produkcji i naciśnij Enter.' WHERE Tag = 'LOC_META_27_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Kontynuuj eksplorację Zwiadowcą. Gdy skończysz wydawać rozkazy Budowniczemu i Zwiadowcy, naciśnij Ctrl plus Spacja, aby zakończyć turę.' WHERE Tag = 'LOC_META_39_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Otwórz Okno wyboru produkcji, wybierając Zmień produkcję na Liście akcji miasta lub naciskając Alt plus Ukośnik wsteczny.' WHERE Tag = 'LOC_META_41b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Osadnika w drzewie produkcji i naciśnij Enter, aby rozpocząć jego szkolenie.' WHERE Tag = 'LOC_META_41_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Procarza w drzewie produkcji i naciśnij Enter. Po wybraniu produkcji naciśnij Ctrl plus Spacja, aby zakończyć turę.' WHERE Tag = 'LOC_META_45_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Budowa pozycji wymaga czasu. Każda pozycja w Oknie wyboru produkcji podaje swój koszt i liczbę tur do ukończenia. Szacunek porównuje koszt [ICON_Production] Produkcji danej pozycji z [ICON_Production] Produkcją miasta na turę. Gdy miasto jest zaznaczone, naciśnij Shift plus 2, aby usłyszeć jego bieżącą produkcję i pozostałe tury.' WHERE Tag = 'LOC_META_5b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Kampus w drzewie produkcji i naciśnij Enter, aby rozpocząć jego budowę w tym mieście.' WHERE Tag = 'LOC_META_80_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Otwórz Zmień produkcję w zaznaczonym mieście za pomocą Alt plus Ukośnik wsteczny lub Listy akcji miasta. Znajdź Bibliotekę w drzewie produkcji i naciśnij Enter.' WHERE Tag = 'LOC_META_87_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Aby wstrzymać jedno zadanie produkcyjne i wyszkolić jednostkę bojową, otwórz Zmień produkcję i wybierz jednostkę w drzewie produkcji. Poprzednia pozycja zachowuje zgromadzony postęp.' WHERE Tag = 'LOC_META_90_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Budowniczego w drzewie produkcji i naciśnij Enter, aby rozpocząć jego szkolenie.' WHERE Tag = 'LOC_META_102_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Teraz to ty decydujesz, co produkuje to miasto. Przydatne opcje w drzewie produkcji to Budowniczy do ulepszeń, jednostka bojowa dla twojej armii lub Spichlerz dla [ICON_Food] Żywności i [ICON_Housing] Obszarów mieszkalnych.' WHERE Tag = 'LOC_META_110_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Zadania blokujące zakończenie tury usłyszysz, naciskając Shift plus Spacja. Naciśnij Ctrl plus Shift plus Spacja, aby otworzyć pełną listę Blokad tury. Produkcja w tym mieście dobiegła końca, więc musisz wybrać, co ma produkować dalej.' WHERE Tag = 'LOC_META_11a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Wybierz produkcję to jedyna obecna blokada tury, więc naciśnij Ctrl plus Spacja, aby otworzyć ją bezpośrednio. Możesz też otworzyć listę Blokad tury za pomocą Ctrl plus Shift plus Spacja, znaleźć Wybierz produkcję i nacisnąć Enter.' WHERE Tag = 'LOC_META_11_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Budowniczy został dodany do Kolejki produkcji miasta. Jego ukończenie zajmie kilka tur. Gdy nie pozostały żadne decyzje, naciśnij Ctrl plus Spacja, aby zakończyć turę.' WHERE Tag = 'LOC_META_13a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Rozpoczęto badanie Garncarstwa. Gdy przesuniesz Zwiadowcę, naciśnij Ctrl plus Spacja, aby zakończyć turę.' WHERE Tag = 'LOC_META_117_BODY' AND Language = 'pl_PL';

-- Badania, idee, ustrój i inne ekrany.
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Spacja, gdy bieżącym działaniem tury jest Wybierz badania, aby otworzyć Okno wyboru badań. Możesz też nacisnąć Ctrl plus Shift plus Spacja, aby otworzyć listę Blokad tury, użyć strzałek w górę i w dół lub wpisać fragment nazwy Wybierz badania, aby znaleźć blokadę badań, a następnie nacisnąć Enter.' WHERE Tag = 'LOC_META_6_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Okno wyboru badań otwiera się na drzewie Dostępne badania. Użyj strzałek w górę i w dół albo wpisz fragment nazwy Górnictwo, aby je znaleźć, a następnie naciśnij Enter, aby rozpocząć jego badanie.' WHERE Tag = 'LOC_META_7_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Garncarstwo w drzewie Dostępne badania i naciśnij Enter.' WHERE Tag = 'LOC_META_33_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Twoja cywilizacja musi zawsze prowadzić badania nad jakąś technologią. Górnictwo zostało ukończone, więc przed zakończeniem tury musisz wybrać kolejną technologię.' WHERE Tag = 'LOC_META_116_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Spacja, gdy bieżącym działaniem tury jest Wybierz badania, aby otworzyć Okno wyboru badań.' WHERE Tag = 'LOC_META_332_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Irygację w drzewie Dostępne badania i naciśnij Enter.' WHERE Tag = 'LOC_META_SELECT_IRRIGATION' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Pismo zostało ukończone, więc wybierz kolejną technologię z drzewa Dostępne badania. Zarówno Hodowla zwierząt, jak i Obróbka brązu to przydatne opcje.' WHERE Tag = 'LOC_META_84_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Odkrycia technologiczne prowadzą do kolejnych technologii poprzez wymagania wstępne. Drzewo technologii pokazuje te ścieżki oraz to, co odblokowuje każda technologia, korzystając z tych samych widoków siatki, drzewa i grafu, które wprowadzono dla idei.' WHERE Tag = 'LOC_META_46_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Shift plus R, aby otworzyć Drzewo technologii.' WHERE Tag = 'LOC_META_46a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Drzewo technologii otwiera się początkowo w widoku siatki, a później zapamiętuje ostatnio wybrany widok. W widoku siatki ery tworzą kolumny, a poziomy badań są uporządkowane od lewej do prawej w obrębie każdej ery. Korzystaj z tej samej nawigacji klawiszami strzałek i wpisywania nazwy, którą wprowadzono w Drzewie idei. Lista rozwijana Widok zawiera opcje Siatka, Graf i Drzewo. Alt plus 1 wybiera Siatkę, Alt plus 2 wybiera Graf, a Alt plus 3 wybiera Drzewo. W widoku grafu strzałka w prawo przechodzi do technologii odblokowywanej przez aktywną technologię, strzałka w lewo do wymagania wstępnego, a strzałka w górę lub w dół przełącza alternatywy z ostatniego połączenia. Czytnik aktywnego elementu pozwala usłyszeć szczegółowe informacje o aktywnej pozycji, sekcja po sekcji. Alt plus strzałka w górę i Alt plus strzałka w dół przechodzą do poprzedniej i następnej sekcji oraz je odczytują, a Alt plus Home i Alt plus End przeskakują do pierwszej i ostatniej sekcji oraz je odczytują.' WHERE Tag = 'LOC_META_47_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Ukończone technologie są ogłaszane jako ukończone w Drzewie technologii. Garncarstwo jest teraz oznaczone jako ukończone.' WHERE Tag = 'LOC_META_48_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Technologie, które można teraz badać, są ogłaszane jako dostępne w Drzewie technologii.' WHERE Tag = 'LOC_META_49_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Technologie, których wymagania wstępne nie zostały spełnione, są ogłaszane jako zablokowane. Użyj Czytnika aktywnego elementu, aby poznać ich wymagania i inne szczegóły. W alternatywnym widoku drzewa możesz też rozwinąć technologię strzałką w prawo, aby przeglądać jej wymagania wstępne, odblokowania i późniejsze technologie w formie gałęzi.' WHERE Tag = 'LOC_META_50_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Pismo w Drzewie technologii i naciśnij Enter, aby rozpocząć jego badanie.' WHERE Tag = 'LOC_META_51_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Pismo jest teraz ogłaszane jako bieżące badanie w Drzewie technologii. Jego podpowiedź zawiera liczbę tur potrzebnych do ukończenia oraz obecny postęp.' WHERE Tag = 'LOC_META_52_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Podpowiedź technologii wymienia również jednostki, budowle, cuda, zdolności i surowce, które odblokowuje lub odkrywa po ukończeniu.' WHERE Tag = 'LOC_META_53A_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Escape, aby zamknąć Drzewo technologii.' WHERE Tag = 'LOC_META_54a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Na liście Panteonów użyj strzałek w górę i w dół albo wpisz fragment nazwy Panteonu, aby go znaleźć. Naciśnij Enter na swoim wyborze, sprawdź okno potwierdzenia, a następnie naciśnij Enter na Zatwierdź panteon.' WHERE Tag = 'LOC_META_129d' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus L, aby otworzyć ekran Religii i jego opcje Panteonu.' WHERE Tag = 'LOC_META_129b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij F3, aby otworzyć ekran [ICON_GreatPerson] Wielkich ludzi. W drzewie Wielkich ludzi użyj klawiszy strzałek lub wpisz fragment imienia osoby, aby znaleźć kandydata do rekrutacji. Naciskaj Tab, aż aktywna będzie opcja Rekrutuj, a następnie naciśnij Enter.' WHERE Tag = 'LOC_META_136b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Rankingi światowe śledzą stan każdego warunku zwycięstwa.' WHERE Tag = 'LOC_META_119_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij F8, aby otworzyć Rankingi światowe.' WHERE Tag = 'LOC_META_119a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Rankingi światowe otwierają się na zakładce Ogólne. Widok tabeli porównuje wszystkich rywali według dostępnych typów zwycięstwa. Użyj Ctrl plus Tab oraz Ctrl plus Shift plus Tab, aby zmieniać zakładki.' WHERE Tag = 'LOC_META_120_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Pozostałe zakładki Rankingów światowych zawierają szczegóły każdego zwycięstwa. Alt plus 1 wybiera tabele na ekranie, a Alt plus 2 wybiera drzewa. Naciśnij Escape, gdy zechcesz kontynuować.' WHERE Tag = 'LOC_META_121_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Jeśli potrzebujesz więcej informacji o czymś w samouczku, naciśnij F1, aby otworzyć Cywilopedię. Sekcja Mod ułatwień dostępu dokumentuje również sterowanie CAI, polecenia rozgrywki i nawigację po ekranach.' WHERE Tag = 'LOC_META_123_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Na ekranie Ustroju naciśnij Ctrl plus Tab, aby przejść do zakładki Doktryny.' WHERE Tag = 'LOC_META_95b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'W zakładce Doktryny użyj klawiszy strzałek, aby znaleźć puste gniazdo wojskowe, i naciśnij Enter. W drzewie wyboru doktryn użyj klawiszy strzałek lub wpisz fragment nazwy Dyscyplina, aby ją znaleźć, a następnie naciśnij Enter. Powtórz to z pustym gniazdem ekonomicznym i Planowaniem miast. Naciskaj Tab, aż aktywna będzie opcja Zatwierdź doktryny, a następnie naciśnij Enter.' WHERE Tag = 'LOC_META_96_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus P, aby otworzyć ekran Ustroju.' WHERE Tag = 'LOC_META_93b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Teraz musisz wybrać nową ideę. Następny krok otwiera Drzewo idei, w którym ścieżki idei są uporządkowane według ery i poziomu badań.' WHERE Tag = 'LOC_META_99a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Ctrl plus Shift plus C, aby otworzyć Drzewo idei.' WHERE Tag = 'LOC_META_99b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Drzewo idei otwiera się początkowo w widoku siatki, a później zapamiętuje ostatnio wybrany widok. Lista rozwijana Widok zawiera opcje Siatka, Graf i Drzewo; Alt plus 1, Alt plus 2 i Alt plus 3 wybierają je w tej kolejności. W widoku siatki używaj strzałek w górę i w dół w obrębie poziomu oraz strzałek w lewo i w prawo między poziomami, albo wpisz fragment nazwy idei, aby ją znaleźć. Rzemiosło to kolejna idea w tym samouczku.' WHERE Tag = 'LOC_META_100_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Znajdź Rzemiosło w Drzewie idei i naciśnij Enter.' WHERE Tag = 'LOC_META_100b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Naciśnij Escape, aby zamknąć Drzewo idei.' WHERE Tag = 'LOC_META_100c_BODY' AND Language = 'pl_PL';

-- Okno wyboru szlaku handlowego.
UPDATE LocalizedText SET Text = 'Okno wyboru szlaku handlowego przedstawia osiągalne miasta w drzewie celów. Użyj strzałek w górę i w dół, aby poruszać się po widocznych celach, oraz strzałek w lewo i w prawo, aby zwijać i rozwijać grupy. Możesz też wpisać fragment nazwy miasta, aby je znaleźć. Gdy Kupiec jest zaznaczony, naciśnij Shift plus 6, aby usłyszeć zasięg jego szlaków lądowych i morskich, lub Shift plus 8, aby usłyszeć jego obecny szlak i plony, jeśli jakiś posiada. Placówka handlowa może wydłużyć zasięg późniejszych szlaków.' WHERE Tag = 'LOC_META_144_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Każdy cel zawiera swoją odległość i plony. Znajdź miasto, które chcesz wybrać, w drzewie celów i naciśnij Enter.' WHERE Tag = 'LOC_META_145b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Sprawdź wybrany szlak w oknie potwierdzenia. Rozpocznij szlak to przycisk domyślny, więc naciśnij Enter, aby rozpocząć szlak. Użyj strzałki w lewo lub w prawo, jeśli musisz przełączać się między opcjami Rozpocznij szlak i Anuluj.' WHERE Tag = 'LOC_META_145c_BODY' AND Language = 'pl_PL';

-- Klawisze informacji przy pierwszym użyciu i późniejsze wskazówki dotyczące konkretnych zagadnień.
UPDATE LocalizedText SET Text = 'Tak jak budowa nowych jednostek jest napędzana [ICON_Production] Produkcją, tak badanie nowych technologii jest napędzane [ICON_Science] Nauką. Naciśnij R, aby usłyszeć swoją Naukę na turę i obecny postęp badań.' WHERE Tag = 'LOC_META_111_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Gromadząc [ICON_Culture] Kulturę, odblokowałeś właśnie Kodeks prawny, który zawiera twój pierwszy ustrój: System wodzowski. Naciśnij P, aby usłyszeć swoją Kulturę na turę i obecny postęp idei.' WHERE Tag = 'LOC_META_93a_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Być może zauważyłeś, że twoje miasta co turę wytwarzają niewielką ilość [ICON_Faith] Wiary.[NEWLINE][NEWLINE][ICON_Faith] Wiarę zdobywa się z czasem dzięki niektórym budowlom, dzielnicom i doktrynom. Naciśnij F, aby usłyszeć swój zapas Wiary i Wiarę na turę.' WHERE Tag = 'LOC_META_128_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Twoje miasto ukończyło produkcję budowli Pomnik. Wszystkie budowle na swój sposób przyczyniają się do rozwoju miasta. Pomnik zwiększa [ICON_Culture] Kulturę wytwarzaną przez miasto, rozszerzając jego wpływy na kolejne pola. Przesuń kursor nawigacji na pole miasta, aby usłyszeć jego budowle wraz z podsumowaniem pola, lub naciśnij tam B, aby odczytać jego budowle i inne szczegóły geograficzne.' WHERE Tag = 'LOC_META_40_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = '[ICON_Citizen] Populacja twojego pierwszego miasta wzrosła z 1 do 2. Dopóki miasto jest dobrze odżywione, a jego mieszkańcy zadowoleni, będzie się nadal rozwijać. [ICON_Citizen] Obywatele miasta obrabiają okoliczne pola i ulepszenia, przyczyniając się do większych plonów. Wyższa [ICON_Citizen] Populacja przyspiesza badania [ICON_Science] Nauki, [ICON_Production] Produkcję miasta oraz rozwój [ICON_Culture] Kultury. Gdy miasto jest zaznaczone, naciśnij Shift plus 6, aby usłyszeć jego populację, obszary mieszkalne i budowle.' WHERE Tag = 'LOC_META_125_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Pamiętaj: Budowniczowie mogą wznosić ulepszenia tylko w granicach twojego miasta.[NEWLINE][NEWLINE]Wytwarzając [ICON_Culture] Kulturę, granice twojego miasta będą się rozszerzać, dając ci dostęp do większej liczby surowców. Gdy miasto jest zaznaczone, naciśnij Shift plus 4, aby usłyszeć postęp rozrostu jego granic.' WHERE Tag = 'LOC_META_38b_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Jednostki dystansowe mają zwykle niższą siłę obrony niż jednostki walczące wręcz, więc trzymaj je blisko przyjaznych jednostek innych typów dla ochrony. Gdy jednostka jest zaznaczona, naciśnij Shift plus 6, aby usłyszeć jej siłę bojową, siłę dystansową lub ostrzału oraz zasięg.' WHERE Tag = 'LOC_META_104_OTHER_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Reszta tego samouczka pomoże ci osiągnąć twoje pierwsze Zwycięstwo przez dominację.[NEWLINE][NEWLINE]Celem Zwycięstwa przez dominację jest bycie ostatnią cywilizacją zajmującą własną [ICON_Capital] Stolicę.[NEWLINE][NEWLINE]W tym samouczku musisz zdobyć [ICON_Capital] Stolicę rywala, jednocześnie nie pozwalając mu zająć twojej.[NEWLINE][NEWLINE]Trzy opcjonalne cele pomogą ci to osiągnąć. Naciśnij Ctrl plus Shift plus T, aby otworzyć listę Celów samouczka. Cele samouczka pojawiają się również w panelu Powiadomień.' WHERE Tag = 'LOC_META_122_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Możesz zrezygnować z [ICON_GreatPerson] Wielkiego człowieka, którego nie chcesz. Inni gracze mogą go wtedy przejąć, decyzji nie da się cofnąć, a twoje [ICON_GreatPerson] Punkty wielkich ludzi zostają zachowane na przyszłą okazję. Ustaw fokus na Wielkim człowieku i naciśnij Delete, aby zrezygnować. Możesz też nacisnąć Tab, aby przejrzeć dostępne przyciski akcji i biografię tej osoby.' WHERE Tag = 'LOC_META_140_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'Twoja cywilizacja może utworzyć ograniczoną liczbę [ICON_TradeRoute] Szlaków handlowych. Dzielnice biznesowe i Dzielnice portowe mogą zwiększyć ten limit. Naciśnij G, aby usłyszeć swój zapas i dochód Złota wraz z aktywnymi Szlakami handlowymi i limitem szlaków.' WHERE Tag = 'LOC_META_142_BODY' AND Language = 'pl_PL';
UPDATE LocalizedText SET Text = 'W trakcie gry zastanawiaj się, jak postępować z sąsiadami, i uważnie ich obserwuj, aby zrozumieć ich strategię. Naciśnij F4, aby otworzyć listę przywódców, których poznałeś, a następnie naciśnij Enter na przywódcy, aby otworzyć poświęcony mu szczegółowy ekran Dyplomacji.' WHERE Tag = 'LOC_META_157_BODY' AND Language = 'pl_PL';
