-- Accessibility-specific instructions for active Firaxis tutorial advisor
-- messages and callout bodies. Gameplay explanations remain vanilla unless
-- their presentation depends on visual or pointer-based information.

-- Unit selection, movement, combat, and actions.
UPDATE LocalizedText SET Text = 'Use Comma or Period to cycle through units that are ready for orders until the Settler is selected.' WHERE Tag = 'LOC_META_1_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'With the Settler selected, press Tab to open the Unit Action List. Use Up and Down Arrow, or type part of Found City to find it, then press Enter. You can also press Alt plus B.' WHERE Tag = 'LOC_META_2_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Use Comma or Period to cycle through units that are ready for orders until the Warrior is selected.' WHERE Tag = 'LOC_META_9_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Military units attack enemy units by moving into their tile. With the Warrior selected, press Alt plus M and move the navigation cursor to the Barbarian Warrior. Press Space to hear the combat preview without committing the attack. It announces the matchup and assessment, predicted damage to both sides, combat strengths, and modifiers. Press Enter once to arm the attack and hear the preview followed by Press again to confirm combat. Press Enter again to attack.' WHERE Tag = 'LOC_META_10_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Warrior units have a [ICON_Movement] Movement range of 2. With the Warrior selected, press Shift plus 2 to hear its remaining movement. For an immediate one-tile move, use Alt plus Q or Alt plus Numpad 7 for northwest, Alt plus E or Alt plus Numpad 9 for northeast, Alt plus A or Alt plus Numpad 4 for west, Alt plus D or Alt plus Numpad 6 for east, Alt plus Z or Alt plus Numpad 1 for southwest, and Alt plus C or Alt plus Numpad 3 for southeast. For a chosen or distant destination, press Alt plus M, move the navigation cursor, press Space for destination information, then press Enter.' WHERE Tag = 'LOC_META_16_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Open terrain, like Plains and Grassland, consumes 1 [ICON_Movement] Movement point, whereas Woods, Hills, and other difficult terrain consume 2 or more. Move the navigation cursor to a tile and press X to hear its movement cost and other physical statistics.' WHERE Tag = 'LOC_META_17_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Alt plus M, move the navigation cursor to the instructed destination, and press Enter to move your Warrior. The World Scanner finds known map objects without checking every tile. When a tutorial world marker appears, its plot is listed in the Tutorial category. Use Control plus Page Up and Control plus Page Down for categories, Shift plus Page Up and Shift plus Page Down for subcategories, Page Up and Page Down for groups, and Alt plus Page Up and Alt plus Page Down for items. Press End to hear the direction and distance to the current result, or Home to move the navigation cursor there.' WHERE Tag = 'LOC_META_17b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'To explore a Tribal Village, move one of your units into its tile. With the Warrior selected, use quick movement or movement mode to enter the Tribal Village tile.' WHERE Tag = 'LOC_META_20_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The Scout has a [ICON_Movement] Movement of 3, allowing it to travel farther than many other units. With the Scout selected, press Shift plus 2 to hear its remaining movement, then use quick movement or movement mode to explore toward unrevealed land.' WHERE Tag = 'LOC_META_21_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'With the Builder selected, use quick movement or movement mode to reach the instructed Plains tile next to your city.' WHERE Tag = 'LOC_META_23_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'With the Builder selected on this tile, press Tab and open the Improvements submenu. This is a new list; use Up and Down Arrow or type part of Farm to find Build Improvement: Farm, then press Enter.' WHERE Tag = 'LOC_META_24_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Builders can build up to 3 improvements before exhausting their workforce. This Builder has used one charge and has 2 remaining. With the Builder selected, press Shift plus 4 whenever you want to hear its remaining charges.' WHERE Tag = 'LOC_META_26_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Units can be given a multi-turn movement order, eliminating the need to issue a separate order on every turn. Select the unit, press Alt plus M, move the navigation cursor to the final destination, and press Enter.' WHERE Tag = 'LOC_META_28a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus S to move the navigation cursor to your current Capital, or find it in the Scanner''s Cities category. Then press Alt plus M, return the cursor to the Capital if necessary, and press Enter to order the Warrior to return there.' WHERE Tag = 'LOC_META_28_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'This Stone is a Bonus resource. It provides an additional +1 [ICON_Production] Production to your city. A Quarry here raises that bonus to +2 [ICON_Production] Production. Move the navigation cursor to a tile and press W to hear its resource, yields, worker, fresh water, and ownership information.' WHERE Tag = 'LOC_META_31a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Use quick movement to move the Builder one tile northeast onto the Stone resource. Once there, press Tab, open the Improvements submenu, find Build Improvement: Quarry, and press Enter.' WHERE Tag = 'LOC_META_31b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Continue exploring with the Scout using quick movement or multi-turn movement orders.' WHERE Tag = 'LOC_META_35_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'With the Warrior selected, press Alt plus F. You can also press Tab, find Fortify in the Unit Action List, and press Enter.' WHERE Tag = 'LOC_META_36_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'When not advancing a military unit, it is often useful to fortify it. Fortifying for up to 2 turns increases its [ICON_Strength] Combat Strength when attacked. Fortify is available in the Unit Action List and also has the shortcut Alt plus F.' WHERE Tag = 'LOC_META_36a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Your Builder still has one charge remaining. Press Shift plus 4 with it selected to hear its charges. You can build either a Mine on the Hill for [ICON_Production] Production or a Farm on the Plains for [ICON_Food] Food. Moving and building may take separate turns.' WHERE Tag = 'LOC_META_38a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'An easy way to move the Settler and Warrior together is to link them into an escort formation. The formation command is in the Unit Action List.' WHERE Tag = 'LOC_META_43a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Select either the Settler or Warrior, press Tab, find Create Escort Formation with the other unit, and press Enter.' WHERE Tag = 'LOC_META_43_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'This destination is several tiles away. Select the formation, press Alt plus M, move the navigation cursor to the instructed destination southeast, and press Enter to issue a movement order. You can use the Scout for open-ended exploration along the route.' WHERE Tag = 'LOC_META_44_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'When the Settler is able, use Found City in the Unit Action List or press Alt plus B. If it has no [ICON_Movement] Movement remaining, end the turn first.' WHERE Tag = 'LOC_META_57_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Each [ICON_GreatPerson] Great Person can activate one or more special bonuses at a required map location. When the Great Person is in the correct place, use Activate Great Person in the Unit Action List. It disappears after using all of its bonuses.' WHERE Tag = 'LOC_META_138_BODY' AND Language = 'en_US';

-- Map exploration, plots, cities, and spoken information.
UPDATE LocalizedText SET Text = 'At the beginning of the game, your city and nearby land are revealed, while the rest of the world is unexplored. Move the navigation cursor with Q, E, A, D, Z, and C, or the matching number-pad directions. Cursor speech identifies unexplored tiles.' WHERE Tag = 'LOC_META_14_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The Warrior has used all of its [ICON_Movement] Movement and is finished for this turn. Press Shift plus 2 with it selected to hear that no movement remains. Production and research are still in progress, so there are no other decisions to make.' WHERE Tag = 'LOC_META_19_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Resources are grouped as Luxury, Strategic, and Bonus resources. Luxury resources provide [ICON_Amenities] Amenities, Strategic resources enable powerful units, and Bonus resources add yields. The Scanner''s Resources category finds known resources by these classes and by resource type. Move the navigation cursor to a tile and press W to hear its resource and yields.' WHERE Tag = 'LOC_META_30_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'In choosing a location for a city, consider nearby [ICON_Food] Food, resources, and fresh water. The Scanner''s Recommendations category lists suitable settlement locations, but the tutorial has already chosen a destination for you, as it does now. Move the navigation cursor through the surrounding land and press W for yields, resources, workers, fresh water, and ownership.' WHERE Tag = 'LOC_META_56_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'A city''s size is represented by its [ICON_Citizen] Population. Select the city and press Tilde for a summary.' WHERE Tag = 'LOC_META_103_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Each city claims surrounding land for your exclusive control. Move the navigation cursor through nearby tiles and press W to hear ownership together with yields and fresh water. The features and resources inside your borders strongly influence the city.' WHERE Tag = 'LOC_META_104_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Each city generates yields from the tiles it works at the start of every turn. Select a city and press Shift plus 7 to hear its total yields. Move the navigation cursor to an individual tile and press W to hear that tile''s yields and worker.' WHERE Tag = 'LOC_META_106_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Each tile within your city borders can provide yields. [ICON_Food] Food fuels city growth, while [ICON_Production] Production builds units, buildings, districts, and wonders. Select the city and press Shift plus 3 for growth or Shift plus 7 for total yields.' WHERE Tag = 'LOC_META_107_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'A tile must be worked by one of your [ICON_Citizen] Citizens to provide its yields, and each Citizen can work one tile. Put the navigation cursor on a tile and press W to hear whether it is worked.' WHERE Tag = 'LOC_META_108_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'When district placement begins, the Scanner''s Valid targets category lists the available placement tiles. Move the navigation cursor among them and press Space for the current tile''s placement information and adjacency details.' WHERE Tag = 'LOC_META_81_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'This tile has Mountains on two edges, providing +2 [ICON_Science] Science per turn to a Campus here. In placement mode, press Space at the navigation cursor to hear the current tile''s placement and adjacency information.' WHERE Tag = 'LOC_META_82_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Move the navigation cursor to the chosen tile, press Space to review its Campus placement information, then press Enter to begin building the Campus.' WHERE Tag = 'LOC_META_83_BODY' AND Language = 'en_US';

-- Production and turn progression.
UPDATE LocalizedText SET Text = 'With the city selected, press Tab to open the City Action List, find Change Production, and press Enter. You can also press Alt plus Backslash.' WHERE Tag = 'LOC_META_3_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The Production Chooser is a tree of units, buildings, districts, and wonders. Use Up and Down Arrow to move through visible items and Left and Right Arrow to collapse or expand categories. You can also type part of an item''s name to find it. Press Enter on the item you want to produce.' WHERE Tag = 'LOC_META_4a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus Space to finish your turn.' WHERE Tag = 'LOC_META_5_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus Space to continue to the next turn.' WHERE Tag = 'LOC_META_13_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus Space once again to continue to the next turn.' WHERE Tag = 'LOC_META_19b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'In addition to training units, a city can construct buildings such as the Monument. Find Monument in the Production tree and press Enter.' WHERE Tag = 'LOC_META_27_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Continue exploring with the Scout. When you have finished giving orders to the Builder and Scout, press Control plus Space to end the turn.' WHERE Tag = 'LOC_META_39_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Open the Production Chooser from Change Production in the City Action List, or with Alt plus Backslash.' WHERE Tag = 'LOC_META_41b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Settler in the Production tree and press Enter to begin training it.' WHERE Tag = 'LOC_META_41_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Slinger in the Production tree and press Enter. When production is chosen, press Control plus Space to end the turn.' WHERE Tag = 'LOC_META_45_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Building items takes time. Each item in the Production Chooser announces its cost and turns to complete. The estimate compares the item''s [ICON_Production] Production cost with the city''s [ICON_Production] Production per turn. With the city selected, press Shift plus 2 to hear its current production and turns remaining.' WHERE Tag = 'LOC_META_5b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Campus in the Production tree and press Enter to begin building one in this city.' WHERE Tag = 'LOC_META_80_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Open Change Production from the selected city with Alt plus Backslash or the City Action List. Find Library in the Production tree and press Enter.' WHERE Tag = 'LOC_META_87_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'To suspend one production task and train a combat unit, open Change Production and choose the unit in the Production tree. The previous item keeps its accumulated progress.' WHERE Tag = 'LOC_META_90_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Builder in the Production tree and press Enter to begin training it.' WHERE Tag = 'LOC_META_102_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'It is now up to you to choose what this city produces. Useful options in the Production tree include a Builder for improvements, a combat unit for your military, or a Granary for [ICON_Food] Food and [ICON_Housing] Housing.' WHERE Tag = 'LOC_META_110_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Tasks that block the end of your turn can be heard with Shift plus Space. Press Control plus Shift plus Space to open the complete Turn Blockers list. Production has finished in this city, so you must choose what it produces next.' WHERE Tag = 'LOC_META_11a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Choose Production is the only current turn blocker, so press Control plus Space to open it directly. You can also open the Turn Blockers list with Control plus Shift plus Space, find Choose Production, and press Enter.' WHERE Tag = 'LOC_META_11_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'A Builder has been added to the city''s Production Queue. It will take several turns to complete. With no decisions remaining, press Control plus Space to end the turn.' WHERE Tag = 'LOC_META_13a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Research on Pottery has begun. Once you have moved the Scout, press Control plus Space to end the turn.' WHERE Tag = 'LOC_META_117_BODY' AND Language = 'en_US';

-- Research, civics, government, and other screens.
UPDATE LocalizedText SET Text = 'Press Control plus Space while Choose Research is the current turn action to open the Research Chooser. You can also press Control plus Shift plus Space for the Turn Blockers list, use Up and Down Arrow or type part of Choose Research to find the research blocker, then press Enter.' WHERE Tag = 'LOC_META_6_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The Research Chooser opens on the Available Research tree. Use Up and Down Arrow, or type part of Mining to find it, then press Enter to begin researching it.' WHERE Tag = 'LOC_META_7_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Pottery in the Available Research tree and press Enter.' WHERE Tag = 'LOC_META_33_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Your civilization must always be researching a technology. Mining is complete, so you must choose the next technology before ending the turn.' WHERE Tag = 'LOC_META_116_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus Space while Choose Research is the current turn action to open the Research Chooser.' WHERE Tag = 'LOC_META_332_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Irrigation in the Available Research tree and press Enter.' WHERE Tag = 'LOC_META_SELECT_IRRIGATION' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Writing is complete, so choose another technology from the Available Research tree. Animal Husbandry and Bronze Working are both useful choices.' WHERE Tag = 'LOC_META_84_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Technological discoveries lead to further technologies through prerequisites. The Technology Tree shows those paths and the things each technology unlocks, using the same grid, tree, and graph views introduced for civics.' WHERE Tag = 'LOC_META_46_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus Shift plus R to open the Technology Tree.' WHERE Tag = 'LOC_META_46a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The Technology Tree initially opens in grid view and remembers the last selected view afterward. In grid view, eras form columns, with research tiers arranged from left to right within each era. Use the same Arrow-key and type-to-find navigation introduced in the Civics Tree. The View dropdown contains Grid, Graph, and Tree. Alt plus 1 selects Grid, Alt plus 2 selects Graph, and Alt plus 3 selects Tree. In graph view, Right follows a technology that the focused technology unlocks, Left follows a prerequisite, and Up or Down cycles the alternatives from the last connection. The Focused Widget Reader lets you hear detailed information about the focused item one section at a time. Alt plus Up Arrow and Alt plus Down Arrow move to and read the previous and next sections, and Alt plus Home and Alt plus End jump to and read the first and last sections.' WHERE Tag = 'LOC_META_47_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Completed technologies are announced as completed in the Technology Tree. Pottery is now marked complete.' WHERE Tag = 'LOC_META_48_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Technologies that can be researched now are announced as available in the Technology Tree.' WHERE Tag = 'LOC_META_49_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Technologies whose prerequisites are incomplete are announced as blocked. Use the Focused Widget Reader to hear their requirements and other details. In the alternate tree view, you can also expand a technology with Right Arrow to browse its prerequisites, unlocks, and later technologies as branches.' WHERE Tag = 'LOC_META_50_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Writing in the Technology Tree and press Enter to begin researching it.' WHERE Tag = 'LOC_META_51_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Writing is now announced as the current research in the Technology Tree. Its tooltip includes the number of turns required to finish it and its current progress.' WHERE Tag = 'LOC_META_52_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'A technology''s tooltip also lists the units, buildings, wonders, abilities, and resources it unlocks or reveals when completed.' WHERE Tag = 'LOC_META_53A_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Escape to close the Technology Tree.' WHERE Tag = 'LOC_META_54a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'In the Pantheon list, use Up and Down Arrow, or type part of a Pantheon''s name to find it. Press Enter on your choice, review the confirmation dialog, then press Enter on Confirm Pantheon.' WHERE Tag = 'LOC_META_129d' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus L to open the Religion screen and its Pantheon choices.' WHERE Tag = 'LOC_META_129b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press F3 to open the [ICON_GreatPerson] Great People screen. In the Great People tree, use the Arrow keys or type part of the person''s name to find the recruitable candidate. Press Tab until Recruit is focused, then press Enter.' WHERE Tag = 'LOC_META_136b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'World Rankings tracks the status of every victory condition.' WHERE Tag = 'LOC_META_119_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press F8 to open World Rankings.' WHERE Tag = 'LOC_META_119a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'World Rankings opens on its Overall tab. Table view compares every competitor across the available victory types. Use Control plus Tab and Control plus Shift plus Tab to change tabs.' WHERE Tag = 'LOC_META_120_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The other World Rankings tabs provide details for each victory. Alt plus 1 selects tables across the screen, and Alt plus 2 selects trees. Press Escape when you are ready to continue.' WHERE Tag = 'LOC_META_121_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'If you need more information about something in the tutorial, press F1 to open the Civilopedia. The Accessibility Mod section also documents CAI controls, gameplay commands, and screen navigation.' WHERE Tag = 'LOC_META_123_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'On the Government screen, press Control plus Tab to switch to the Policies tab.' WHERE Tag = 'LOC_META_95b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'On the Policies tab, use the Arrow keys to find the empty Military slot and press Enter. In the policy picker tree, use the Arrow keys or type part of Discipline to find it, then press Enter. Repeat with the empty Economic slot and Urban Planning. Press Tab until Confirm Policies is focused, then press Enter.' WHERE Tag = 'LOC_META_96_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus P to open the Government screen.' WHERE Tag = 'LOC_META_93b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'You now need to choose a new civic. The next step opens the Civics Tree, where civic paths are arranged by era and research tier.' WHERE Tag = 'LOC_META_99a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Control plus Shift plus C to open the Civics Tree.' WHERE Tag = 'LOC_META_99b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The Civics Tree initially opens in grid view and remembers the last selected view afterward. The View dropdown contains Grid, Graph, and Tree; Alt plus 1, Alt plus 2, and Alt plus 3 select them in that order. In grid view, use Up and Down Arrow within a tier and Left and Right Arrow between tiers, or type part of a civic''s name to find it. Craftsmanship is the next civic for this tutorial.' WHERE Tag = 'LOC_META_100_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Find Craftsmanship in the Civics Tree and press Enter.' WHERE Tag = 'LOC_META_100b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Press Escape to close the Civics Tree.' WHERE Tag = 'LOC_META_100c_BODY' AND Language = 'en_US';

-- Trade Route Chooser.
UPDATE LocalizedText SET Text = 'The Trade Route Chooser presents reachable cities in a destination tree. Use Up and Down Arrow to move through visible destinations and Left and Right Arrow to collapse or expand groups. You can also type part of a city''s name to find it. With a Trader selected, press Shift plus 6 to hear its land and sea route range, or Shift plus 8 to hear its current route and yields if it has one. A Trading Post can extend later routes farther.' WHERE Tag = 'LOC_META_144_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Each destination includes its distance and yields. Find the city you want in the destination tree and press Enter.' WHERE Tag = 'LOC_META_145b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Review the selected route in the confirmation dialog. Begin Route is the default button, so press Enter to start the route. Use Left or Right Arrow if you need to move between Begin Route and Cancel.' WHERE Tag = 'LOC_META_145c_BODY' AND Language = 'en_US';

-- First-use information keys and later concept-specific guidance.
UPDATE LocalizedText SET Text = 'Just as building new units is fueled by [ICON_Production] Production, researching new technologies is fueled by [ICON_Science] Science. Press R to hear your Science per turn and current research progress.' WHERE Tag = 'LOC_META_111_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'By accumulating [ICON_Culture] Culture, you have just unlocked Code of Laws, which contains your first government: Chiefdom. Press P to hear your Culture per turn and current civic progress.' WHERE Tag = 'LOC_META_93a_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'You may have noticed that your cities have been generating a small amount of [ICON_Faith] Faith each turn.[NEWLINE][NEWLINE][ICON_Faith] Faith is earned over time from certain buildings, districts, and policies. Press F to hear your Faith balance and Faith per turn.' WHERE Tag = 'LOC_META_128_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Your city has finished production on the Monument building. All buildings contribute to a city''s development in specific ways. The Monument increases the [ICON_Culture] Culture generated by the city, extending its influence over additional hexes. Move the navigation cursor onto the city tile to hear its buildings with the tile summary, or press B there to read its buildings and other geographic details.' WHERE Tag = 'LOC_META_40_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The [ICON_Citizen] Population of your first city has grown from 1 to 2. As long as a city is well fed and its people are happy, it will continue to grow. The [ICON_Citizen] Citizens of the city work the surrounding plots and improvements, contributing to greater yields. Higher [ICON_Citizen] Populations contribute to faster [ICON_Science] Science research, faster city [ICON_Production] Production, and faster [ICON_Culture] Cultural growth. With the city selected, press Shift plus 6 to hear its population, housing, and buildings.' WHERE Tag = 'LOC_META_125_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Remember: Builders can only construct improvements within the borders of your city.[NEWLINE][NEWLINE]By generating [ICON_Culture] Culture, the borders of your city will expand, allowing you access to more resources. With the city selected, press Shift plus 4 to hear its border-growth progress.' WHERE Tag = 'LOC_META_38b_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Ranged units tend to have lower defense strength than melee units, so keep them close to friendly units of other types for protection. With a unit selected, press Shift plus 6 to hear its combat strength, ranged or bombard strength, and range.' WHERE Tag = 'LOC_META_104_OTHER_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'The rest of this tutorial will help you achieve your first Domination Victory.[NEWLINE][NEWLINE]The goal of a Domination Victory is for your civilization to be the last to occupy its own [ICON_Capital] Capital city.[NEWLINE][NEWLINE]For this tutorial, you must capture your rival''s [ICON_Capital] Capital while preventing them from taking yours.[NEWLINE][NEWLINE]Three optional objectives will help you achieve this. Press Control plus Shift plus T to open the Tutorial Goals list. Tutorial goals also appear in the Notifications panel.' WHERE Tag = 'LOC_META_122_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'You can pass on a [ICON_GreatPerson] Great Person you do not want. Other players may then claim them, the decision cannot be reversed, and your [ICON_GreatPerson] Great People Points are saved for a future opportunity. Focus the Great Person and press Delete to pass. Alternatively, press Tab to browse that person''s available action buttons and biography.' WHERE Tag = 'LOC_META_140_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'Your civilization can establish a limited number of [ICON_TradeRoute] Trade Routes. Commercial Hub and Harbor districts can increase this capacity. Press G to hear your Gold balance and income together with your active Trade Routes and route capacity.' WHERE Tag = 'LOC_META_142_BODY' AND Language = 'en_US';
UPDATE LocalizedText SET Text = 'As you play, consider how to deal with your neighbors and watch them carefully to understand their strategy. Press F4 to open the list of leaders you have met, then press Enter on a leader to open the detailed Diplomacy screen for them.' WHERE Tag = 'LOC_META_157_BODY' AND Language = 'en_US';
