-- Accessibility-specific instructions for active Firaxis tutorial advisor
-- messages and callout bodies. Gameplay explanations remain vanilla unless
-- their presentation depends on visual or pointer-based information.

-- Unit selection, movement, combat, and actions.
UPDATE LocalizedText SET Text = 'Utilisez Virgule ou Point pour faire défiler les unités prêtes à recevoir des ordres jusqu''à ce que le Colon soit sélectionné.' WHERE Tag = 'LOC_META_1_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le Colon étant sélectionné, appuyez sur Tab pour ouvrir la liste d''actions de l''unité. Utilisez les flèches Haut et Bas, ou tapez une partie de Fonder une ville pour la trouver, puis appuyez sur Entrée. Vous pouvez aussi appuyer sur Alt plus B.' WHERE Tag = 'LOC_META_2_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Utilisez Virgule ou Point pour faire défiler les unités prêtes à recevoir des ordres jusqu''à ce que le Guerrier soit sélectionné.' WHERE Tag = 'LOC_META_9_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les unités militaires attaquent les unités ennemies en se déplaçant sur leur case. Le Guerrier étant sélectionné, appuyez sur Alt plus M et amenez le curseur de navigation sur le Guerrier barbare. Appuyez sur Espace pour entendre l''aperçu de combat sans lancer l''attaque. Il annonce la confrontation et son évaluation, les dégâts prévus des deux côtés, les forces de combat et les modificateurs. Appuyez une fois sur Entrée pour armer l''attaque et entendre l''aperçu suivi de « Appuyez de nouveau pour confirmer le combat ». Appuyez de nouveau sur Entrée pour attaquer.' WHERE Tag = 'LOC_META_10_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les Guerriers ont une portée de [ICON_Movement] Déplacement de 2. Le Guerrier étant sélectionné, appuyez sur Maj plus 2 pour entendre son déplacement restant. Pour un déplacement immédiat d''une case, utilisez Alt plus Q ou Alt plus pavé numérique 7 pour le nord-ouest, Alt plus E ou Alt plus pavé numérique 9 pour le nord-est, Alt plus A ou Alt plus pavé numérique 4 pour l''ouest, Alt plus D ou Alt plus pavé numérique 6 pour l''est, Alt plus Z ou Alt plus pavé numérique 1 pour le sud-ouest, et Alt plus C ou Alt plus pavé numérique 3 pour le sud-est. Pour une destination choisie ou éloignée, appuyez sur Alt plus M, déplacez le curseur de navigation, appuyez sur Espace pour les informations de destination, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_16_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Un terrain dégagé, comme les Plaines et les Prairies, coûte 1 point de [ICON_Movement] Déplacement, tandis que les Bois, les Collines et les autres terrains difficiles en coûtent 2 ou plus. Amenez le curseur de navigation sur une case et appuyez sur X pour entendre son coût de déplacement et ses autres caractéristiques physiques.' WHERE Tag = 'LOC_META_17_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Alt plus M, amenez le curseur de navigation sur la destination indiquée, puis appuyez sur Entrée pour déplacer votre Guerrier. Le scanner du monde trouve les objets connus de la carte sans avoir à vérifier chaque case. Lorsqu''un marqueur de tutoriel apparaît sur la carte, sa case figure dans la catégorie Tutoriel. Utilisez Ctrl plus Page précédente et Ctrl plus Page suivante pour les catégories, Maj plus Page précédente et Maj plus Page suivante pour les sous-catégories, Page précédente et Page suivante pour les groupes, et Alt plus Page précédente et Alt plus Page suivante pour les éléments. Appuyez sur Fin pour entendre la direction et la distance jusqu''au résultat actuel, ou sur Début pour y amener le curseur de navigation.' WHERE Tag = 'LOC_META_17b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Pour explorer un Village tribal, déplacez l''une de vos unités sur sa case. Le Guerrier étant sélectionné, utilisez le déplacement rapide ou le mode de déplacement pour entrer sur la case du Village tribal.' WHERE Tag = 'LOC_META_20_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'L''Éclaireur a un [ICON_Movement] Déplacement de 3, ce qui lui permet de parcourir de plus grandes distances que beaucoup d''autres unités. L''Éclaireur étant sélectionné, appuyez sur Maj plus 2 pour entendre son déplacement restant, puis utilisez le déplacement rapide ou le mode de déplacement pour explorer les terres inconnues.' WHERE Tag = 'LOC_META_21_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le Bâtisseur étant sélectionné, utilisez le déplacement rapide ou le mode de déplacement pour atteindre la case de Plaines indiquée à côté de votre ville.' WHERE Tag = 'LOC_META_23_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le Bâtisseur étant sélectionné sur cette case, appuyez sur Tab et ouvrez le sous-menu Aménagements. Il s''agit d''une nouvelle liste ; utilisez les flèches Haut et Bas ou tapez une partie de Ferme pour trouver Construire l''aménagement : Ferme, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_24_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les Bâtisseurs peuvent construire jusqu''à 3 aménagements avant d''épuiser leur main-d''œuvre. Ce Bâtisseur a utilisé une charge et il lui en reste 2. Le Bâtisseur étant sélectionné, appuyez sur Maj plus 4 chaque fois que vous voulez entendre ses charges restantes.' WHERE Tag = 'LOC_META_26_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'On peut donner à une unité un ordre de déplacement sur plusieurs tours, ce qui évite d''avoir à donner un ordre distinct à chaque tour. Sélectionnez l''unité, appuyez sur Alt plus M, amenez le curseur de navigation jusqu''à la destination finale, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_28a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus S pour amener le curseur de navigation sur votre Capitale actuelle, ou trouvez-la dans la catégorie Villes du scanner. Appuyez ensuite sur Alt plus M, ramenez si nécessaire le curseur sur la Capitale, puis appuyez sur Entrée pour ordonner au Guerrier d''y retourner.' WHERE Tag = 'LOC_META_28_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Cette Pierre est une ressource bonus. Elle fournit +1 [ICON_Production] Production supplémentaire à votre ville. Une Carrière ici porte ce bonus à +2 [ICON_Production] Production. Amenez le curseur de navigation sur une case et appuyez sur W pour entendre sa ressource, ses rendements, son travailleur, la présence d''eau douce et les informations de propriété.' WHERE Tag = 'LOC_META_31a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Utilisez le déplacement rapide pour déplacer le Bâtisseur d''une case vers le nord-est, sur la ressource Pierre. Une fois sur place, appuyez sur Tab, ouvrez le sous-menu Aménagements, trouvez Construire l''aménagement : Carrière, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_31b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Continuez à explorer avec l''Éclaireur en utilisant le déplacement rapide ou les ordres de déplacement sur plusieurs tours.' WHERE Tag = 'LOC_META_35_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le Guerrier étant sélectionné, appuyez sur Alt plus F. Vous pouvez aussi appuyer sur Tab, trouver Se retrancher dans la liste d''actions de l''unité, puis appuyer sur Entrée.' WHERE Tag = 'LOC_META_36_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Lorsqu''une unité militaire n''avance pas, il est souvent utile de la retrancher. Se retrancher pendant 2 tours au maximum augmente sa [ICON_Strength] Force de combat lorsqu''elle est attaquée. Se retrancher est disponible dans la liste d''actions de l''unité et dispose aussi du raccourci Alt plus F.' WHERE Tag = 'LOC_META_36a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Votre Bâtisseur a encore une charge. Appuyez sur Maj plus 4 lorsqu''il est sélectionné pour entendre ses charges. Vous pouvez construire soit une Mine sur la Colline pour de la [ICON_Production] Production, soit une Ferme sur les Plaines pour de la [ICON_Food] Nourriture. Le déplacement et la construction peuvent nécessiter des tours distincts.' WHERE Tag = 'LOC_META_38a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Un moyen simple de déplacer ensemble le Colon et le Guerrier consiste à les lier dans une formation d''escorte. La commande de formation se trouve dans la liste d''actions de l''unité.' WHERE Tag = 'LOC_META_43a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Sélectionnez le Colon ou le Guerrier, appuyez sur Tab, trouvez Créer une formation d''escorte avec l''autre unité, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_43_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Cette destination se trouve à plusieurs cases. Sélectionnez la formation, appuyez sur Alt plus M, amenez le curseur de navigation sur la destination indiquée au sud-est, puis appuyez sur Entrée pour donner un ordre de déplacement. Vous pouvez utiliser l''Éclaireur pour explorer librement le long du trajet.' WHERE Tag = 'LOC_META_44_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Dès que le Colon le peut, utilisez Fonder une ville dans la liste d''actions de l''unité ou appuyez sur Alt plus B. S''il ne lui reste plus de [ICON_Movement] Déplacement, terminez d''abord le tour.' WHERE Tag = 'LOC_META_57_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Chaque [ICON_GreatPerson] Personnage illustre peut activer un ou plusieurs bonus spéciaux à un endroit précis de la carte. Lorsque le Personnage illustre est au bon endroit, utilisez Activer le personnage illustre dans la liste d''actions de l''unité. Il disparaît après avoir utilisé tous ses bonus.' WHERE Tag = 'LOC_META_138_BODY' AND Language = 'fr_FR';

-- Map exploration, plots, cities, and spoken information.
UPDATE LocalizedText SET Text = 'Au début de la partie, votre ville et les terres proches sont révélées, tandis que le reste du monde est inexploré. Déplacez le curseur de navigation avec Q, E, A, D, Z et C, ou les directions correspondantes du pavé numérique. La voix du curseur signale les cases inexplorées.' WHERE Tag = 'LOC_META_14_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le Guerrier a utilisé tout son [ICON_Movement] Déplacement et a terminé pour ce tour. Appuyez sur Maj plus 2 lorsqu''il est sélectionné pour entendre qu''il ne lui reste aucun déplacement. La production et la recherche sont toujours en cours, il n''y a donc aucune autre décision à prendre.' WHERE Tag = 'LOC_META_19_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les ressources sont regroupées en ressources de luxe, stratégiques et bonus. Les ressources de luxe fournissent des [ICON_Amenities] Activités, les ressources stratégiques permettent de puissantes unités, et les ressources bonus ajoutent des rendements. La catégorie Ressources du scanner trouve les ressources connues par ces classes et par type de ressource. Amenez le curseur de navigation sur une case et appuyez sur W pour entendre sa ressource et ses rendements.' WHERE Tag = 'LOC_META_30_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Pour choisir l''emplacement d''une ville, tenez compte de la [ICON_Food] Nourriture, des ressources et de l''eau douce à proximité. La catégorie Recommandations du scanner répertorie les emplacements de peuplement adaptés, mais le tutoriel a déjà choisi une destination pour vous, comme c''est le cas ici. Déplacez le curseur de navigation à travers les terres environnantes et appuyez sur W pour les rendements, les ressources, les travailleurs, l''eau douce et la propriété.' WHERE Tag = 'LOC_META_56_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'La taille d''une ville est représentée par sa [ICON_Citizen] Population. Sélectionnez la ville et appuyez sur Tilde pour un résumé.' WHERE Tag = 'LOC_META_103_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Chaque ville revendique les terres environnantes pour votre contrôle exclusif. Déplacez le curseur de navigation à travers les cases proches et appuyez sur W pour entendre la propriété ainsi que les rendements et l''eau douce. Les caractéristiques et les ressources situées à l''intérieur de vos frontières influencent fortement la ville.' WHERE Tag = 'LOC_META_104_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Chaque ville génère des rendements à partir des cases qu''elle exploite au début de chaque tour. Sélectionnez une ville et appuyez sur Maj plus 7 pour entendre ses rendements totaux. Amenez le curseur de navigation sur une case individuelle et appuyez sur W pour entendre les rendements et le travailleur de cette case.' WHERE Tag = 'LOC_META_106_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Chaque case située à l''intérieur des frontières de votre ville peut fournir des rendements. La [ICON_Food] Nourriture alimente la croissance de la ville, tandis que la [ICON_Production] Production permet de construire des unités, des bâtiments, des quartiers et des merveilles. Sélectionnez la ville et appuyez sur Maj plus 3 pour la croissance ou sur Maj plus 7 pour les rendements totaux.' WHERE Tag = 'LOC_META_107_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Une case doit être exploitée par l''un de vos [ICON_Citizen] Citoyens pour fournir ses rendements, et chaque Citoyen peut exploiter une case. Placez le curseur de navigation sur une case et appuyez sur W pour entendre si elle est exploitée.' WHERE Tag = 'LOC_META_108_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Lorsque le placement d''un quartier commence, la catégorie Cibles valides du scanner répertorie les cases de placement disponibles. Déplacez le curseur de navigation parmi elles et appuyez sur Espace pour les informations de placement de la case actuelle et les détails d''adjacence.' WHERE Tag = 'LOC_META_81_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Cette case a des Montagnes sur deux de ses bords, ce qui fournit +2 [ICON_Science] Science par tour à un Campus placé ici. En mode de placement, appuyez sur Espace au niveau du curseur de navigation pour entendre les informations de placement et d''adjacence de la case actuelle.' WHERE Tag = 'LOC_META_82_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Amenez le curseur de navigation sur la case choisie, appuyez sur Espace pour revoir ses informations de placement de Campus, puis appuyez sur Entrée pour commencer à construire le Campus.' WHERE Tag = 'LOC_META_83_BODY' AND Language = 'fr_FR';

-- Production and turn progression.
UPDATE LocalizedText SET Text = 'La ville étant sélectionnée, appuyez sur Tab pour ouvrir la liste d''actions de la ville, trouvez Changer la production, puis appuyez sur Entrée. Vous pouvez aussi appuyer sur Alt plus Barre oblique inverse.' WHERE Tag = 'LOC_META_3_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le sélecteur de production est une arborescence d''unités, de bâtiments, de quartiers et de merveilles. Utilisez les flèches Haut et Bas pour parcourir les éléments visibles et les flèches Gauche et Droite pour réduire ou développer les catégories. Vous pouvez aussi taper une partie du nom d''un élément pour le trouver. Appuyez sur Entrée sur l''élément que vous voulez produire.' WHERE Tag = 'LOC_META_4a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus Espace pour terminer votre tour.' WHERE Tag = 'LOC_META_5_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus Espace pour passer au tour suivant.' WHERE Tag = 'LOC_META_13_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez de nouveau sur Ctrl plus Espace pour passer au tour suivant.' WHERE Tag = 'LOC_META_19b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'En plus de former des unités, une ville peut construire des bâtiments comme le Monument. Trouvez Monument dans l''arbre de production et appuyez sur Entrée.' WHERE Tag = 'LOC_META_27_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Continuez à explorer avec l''Éclaireur. Lorsque vous avez fini de donner des ordres au Bâtisseur et à l''Éclaireur, appuyez sur Ctrl plus Espace pour terminer le tour.' WHERE Tag = 'LOC_META_39_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Ouvrez le sélecteur de production depuis Changer la production dans la liste d''actions de la ville, ou avec Alt plus Barre oblique inverse.' WHERE Tag = 'LOC_META_41b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Colon dans l''arbre de production et appuyez sur Entrée pour commencer à le former.' WHERE Tag = 'LOC_META_41_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Frondeur dans l''arbre de production et appuyez sur Entrée. Une fois la production choisie, appuyez sur Ctrl plus Espace pour terminer le tour.' WHERE Tag = 'LOC_META_45_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'La construction des éléments prend du temps. Chaque élément du sélecteur de production annonce son coût et le nombre de tours nécessaires. L''estimation compare le coût en [ICON_Production] Production de l''élément à la [ICON_Production] Production par tour de la ville. La ville étant sélectionnée, appuyez sur Maj plus 2 pour entendre sa production actuelle et les tours restants.' WHERE Tag = 'LOC_META_5b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Campus dans l''arbre de production et appuyez sur Entrée pour en commencer un dans cette ville.' WHERE Tag = 'LOC_META_80_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Ouvrez Changer la production depuis la ville sélectionnée avec Alt plus Barre oblique inverse ou la liste d''actions de la ville. Trouvez Bibliothèque dans l''arbre de production et appuyez sur Entrée.' WHERE Tag = 'LOC_META_87_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Pour suspendre une tâche de production et former une unité de combat, ouvrez Changer la production et choisissez l''unité dans l''arbre de production. L''élément précédent conserve la progression accumulée.' WHERE Tag = 'LOC_META_90_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Bâtisseur dans l''arbre de production et appuyez sur Entrée pour commencer à le former.' WHERE Tag = 'LOC_META_102_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'C''est désormais à vous de choisir ce que cette ville produit. Parmi les options utiles de l''arbre de production figurent un Bâtisseur pour les aménagements, une unité de combat pour votre armée, ou un Grenier pour de la [ICON_Food] Nourriture et des [ICON_Housing] Habitations.' WHERE Tag = 'LOC_META_110_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les tâches qui bloquent la fin de votre tour peuvent être entendues avec Maj plus Espace. Appuyez sur Ctrl plus Maj plus Espace pour ouvrir la liste complète des bloqueurs de tour. La production est terminée dans cette ville, vous devez donc choisir ce qu''elle produit ensuite.' WHERE Tag = 'LOC_META_11a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Choisir la production est le seul bloqueur de tour actuel ; appuyez donc sur Ctrl plus Espace pour l''ouvrir directement. Vous pouvez aussi ouvrir la liste des bloqueurs de tour avec Ctrl plus Maj plus Espace, trouver Choisir la production, puis appuyer sur Entrée.' WHERE Tag = 'LOC_META_11_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Un Bâtisseur a été ajouté à la file de production de la ville. Il faudra plusieurs tours pour le terminer. Comme il ne reste aucune décision à prendre, appuyez sur Ctrl plus Espace pour terminer le tour.' WHERE Tag = 'LOC_META_13a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'La recherche de la Poterie a commencé. Une fois l''Éclaireur déplacé, appuyez sur Ctrl plus Espace pour terminer le tour.' WHERE Tag = 'LOC_META_117_BODY' AND Language = 'fr_FR';

-- Research, civics, government, and other screens.
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus Espace tant que Choisir la recherche est l''action de tour actuelle pour ouvrir le sélecteur de recherche. Vous pouvez aussi appuyer sur Ctrl plus Maj plus Espace pour la liste des bloqueurs de tour, utiliser les flèches Haut et Bas ou taper une partie de Choisir la recherche pour trouver le bloqueur de recherche, puis appuyer sur Entrée.' WHERE Tag = 'LOC_META_6_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le sélecteur de recherche s''ouvre sur l''arbre des recherches disponibles. Utilisez les flèches Haut et Bas, ou tapez une partie d''Exploitation minière pour la trouver, puis appuyez sur Entrée pour commencer à la rechercher.' WHERE Tag = 'LOC_META_7_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Poterie dans l''arbre des recherches disponibles et appuyez sur Entrée.' WHERE Tag = 'LOC_META_33_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Votre civilisation doit toujours être en train de rechercher une technologie. L''Exploitation minière est terminée, vous devez donc choisir la prochaine technologie avant de terminer le tour.' WHERE Tag = 'LOC_META_116_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus Espace tant que Choisir la recherche est l''action de tour actuelle pour ouvrir le sélecteur de recherche.' WHERE Tag = 'LOC_META_332_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Irrigation dans l''arbre des recherches disponibles et appuyez sur Entrée.' WHERE Tag = 'LOC_META_SELECT_IRRIGATION' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'L''Écriture est terminée ; choisissez donc une autre technologie dans l''arbre des recherches disponibles. L''Élevage et le Travail du bronze sont deux choix utiles.' WHERE Tag = 'LOC_META_84_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les découvertes technologiques mènent à d''autres technologies par le biais de prérequis. L''arbre technologique montre ces chemins et ce que chaque technologie débloque, en utilisant les mêmes vues grille, arbre et graphe que celles présentées pour les dogmes.' WHERE Tag = 'LOC_META_46_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus Maj plus R pour ouvrir l''arbre technologique.' WHERE Tag = 'LOC_META_46a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'L''arbre technologique s''ouvre d''abord en vue grille et retient ensuite la dernière vue sélectionnée. En vue grille, les ères forment des colonnes, les paliers de recherche étant disposés de gauche à droite au sein de chaque ère. Utilisez la même navigation par flèches et par saisie que celle présentée dans l''arbre des dogmes. Le menu déroulant Vue contient Grille, Graphe et Arbre. Alt plus 1 sélectionne Grille, Alt plus 2 sélectionne Graphe, et Alt plus 3 sélectionne Arbre. En vue graphe, Droite suit une technologie que la technologie ciblée débloque, Gauche suit un prérequis, et Haut ou Bas fait défiler les alternatives depuis la dernière connexion. Le lecteur de widget ciblé vous permet d''entendre des informations détaillées sur l''élément ciblé, une section à la fois. Alt plus flèche Haut et Alt plus flèche Bas se déplacent vers la section précédente et la section suivante et les lisent, et Alt plus Début et Alt plus Fin sautent à la première et à la dernière section et les lisent.' WHERE Tag = 'LOC_META_47_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les technologies terminées sont annoncées comme terminées dans l''arbre technologique. La Poterie est maintenant marquée comme terminée.' WHERE Tag = 'LOC_META_48_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les technologies pouvant être recherchées immédiatement sont annoncées comme disponibles dans l''arbre technologique.' WHERE Tag = 'LOC_META_49_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les technologies dont les prérequis ne sont pas remplis sont annoncées comme bloquées. Utilisez le lecteur de widget ciblé pour entendre leurs conditions et d''autres détails. Dans la vue arbre alternative, vous pouvez aussi développer une technologie avec la flèche Droite pour parcourir ses prérequis, ses déblocages et les technologies ultérieures sous forme de branches.' WHERE Tag = 'LOC_META_50_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Écriture dans l''arbre technologique et appuyez sur Entrée pour commencer à la rechercher.' WHERE Tag = 'LOC_META_51_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'L''Écriture est désormais annoncée comme la recherche en cours dans l''arbre technologique. Son infobulle indique le nombre de tours nécessaires pour la terminer et sa progression actuelle.' WHERE Tag = 'LOC_META_52_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'L''infobulle d''une technologie répertorie aussi les unités, bâtiments, merveilles, capacités et ressources qu''elle débloque ou révèle une fois terminée.' WHERE Tag = 'LOC_META_53A_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Échap pour fermer l''arbre technologique.' WHERE Tag = 'LOC_META_54a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Dans la liste des Panthéons, utilisez les flèches Haut et Bas, ou tapez une partie du nom d''un Panthéon pour le trouver. Appuyez sur Entrée sur votre choix, examinez la boîte de dialogue de confirmation, puis appuyez sur Entrée sur Confirmer le panthéon.' WHERE Tag = 'LOC_META_129d' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus L pour ouvrir l''écran de la Religion et ses choix de Panthéon.' WHERE Tag = 'LOC_META_129b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur F3 pour ouvrir l''écran des [ICON_GreatPerson] Personnages illustres. Dans l''arbre des personnages illustres, utilisez les flèches ou tapez une partie du nom de la personne pour trouver le candidat recrutable. Appuyez sur Tab jusqu''à ce que Recruter soit ciblé, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_136b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les Classements mondiaux suivent l''état de chaque condition de victoire.' WHERE Tag = 'LOC_META_119_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur F8 pour ouvrir les Classements mondiaux.' WHERE Tag = 'LOC_META_119a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les Classements mondiaux s''ouvrent sur leur onglet Vue d''ensemble. La vue tableau compare tous les concurrents selon les types de victoire disponibles. Utilisez Ctrl plus Tab et Ctrl plus Maj plus Tab pour changer d''onglet.' WHERE Tag = 'LOC_META_120_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les autres onglets des Classements mondiaux fournissent des détails pour chaque victoire. Alt plus 1 sélectionne les tableaux à l''échelle de l''écran, et Alt plus 2 sélectionne les arbres. Appuyez sur Échap lorsque vous êtes prêt à continuer.' WHERE Tag = 'LOC_META_121_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Si vous avez besoin de plus d''informations sur un élément du tutoriel, appuyez sur F1 pour ouvrir la Civilopédia. La section Mod d''accessibilité documente aussi les commandes de CAI, les commandes de jeu et la navigation entre les écrans.' WHERE Tag = 'LOC_META_123_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Sur l''écran du Gouvernement, appuyez sur Ctrl plus Tab pour passer à l''onglet Doctrines.' WHERE Tag = 'LOC_META_95b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Dans l''onglet Doctrines, utilisez les flèches pour trouver l''emplacement Militaire vide et appuyez sur Entrée. Dans l''arbre de sélection des doctrines, utilisez les flèches ou tapez une partie de Discipline pour la trouver, puis appuyez sur Entrée. Répétez avec l''emplacement Économique vide et Urbanisme. Appuyez sur Tab jusqu''à ce que Confirmer les doctrines soit ciblé, puis appuyez sur Entrée.' WHERE Tag = 'LOC_META_96_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus P pour ouvrir l''écran du Gouvernement.' WHERE Tag = 'LOC_META_93b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Vous devez maintenant choisir un nouveau dogme. L''étape suivante ouvre l''arbre des dogmes, où les chemins de dogmes sont classés par ère et par palier de recherche.' WHERE Tag = 'LOC_META_99a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Ctrl plus Maj plus C pour ouvrir l''arbre des dogmes.' WHERE Tag = 'LOC_META_99b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'L''arbre des dogmes s''ouvre d''abord en vue grille et retient ensuite la dernière vue sélectionnée. Le menu déroulant Vue contient Grille, Graphe et Arbre ; Alt plus 1, Alt plus 2 et Alt plus 3 les sélectionnent dans cet ordre. En vue grille, utilisez les flèches Haut et Bas au sein d''un palier et les flèches Gauche et Droite entre les paliers, ou tapez une partie du nom d''un dogme pour le trouver. Artisanat est le prochain dogme de ce tutoriel.' WHERE Tag = 'LOC_META_100_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Trouvez Artisanat dans l''arbre des dogmes et appuyez sur Entrée.' WHERE Tag = 'LOC_META_100b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Appuyez sur Échap pour fermer l''arbre des dogmes.' WHERE Tag = 'LOC_META_100c_BODY' AND Language = 'fr_FR';

-- Trade Route Chooser.
UPDATE LocalizedText SET Text = 'Le sélecteur de route commerciale présente les villes accessibles dans une arborescence de destinations. Utilisez les flèches Haut et Bas pour parcourir les destinations visibles et les flèches Gauche et Droite pour réduire ou développer les groupes. Vous pouvez aussi taper une partie du nom d''une ville pour la trouver. Un Négociant étant sélectionné, appuyez sur Maj plus 6 pour entendre sa portée de route terrestre et maritime, ou sur Maj plus 8 pour entendre sa route actuelle et ses rendements s''il en a une. Un Comptoir commercial peut prolonger les routes ultérieures.' WHERE Tag = 'LOC_META_144_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Chaque destination indique sa distance et ses rendements. Trouvez la ville que vous voulez dans l''arborescence des destinations et appuyez sur Entrée.' WHERE Tag = 'LOC_META_145b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Examinez la route sélectionnée dans la boîte de dialogue de confirmation. Commencer la route est le bouton par défaut ; appuyez donc sur Entrée pour démarrer la route. Utilisez la flèche Gauche ou Droite si vous devez passer entre Commencer la route et Annuler.' WHERE Tag = 'LOC_META_145c_BODY' AND Language = 'fr_FR';

-- First-use information keys and later concept-specific guidance.
UPDATE LocalizedText SET Text = 'Tout comme la construction de nouvelles unités est alimentée par la [ICON_Production] Production, la recherche de nouvelles technologies est alimentée par la [ICON_Science] Science. Appuyez sur R pour entendre votre Science par tour et la progression de votre recherche actuelle.' WHERE Tag = 'LOC_META_111_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'En accumulant de la [ICON_Culture] Culture, vous venez de débloquer Code juridique, qui contient votre premier gouvernement : Chefferie. Appuyez sur P pour entendre votre Culture par tour et la progression de votre dogme actuel.' WHERE Tag = 'LOC_META_93a_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Vous avez peut-être remarqué que vos villes génèrent une petite quantité de [ICON_Faith] Foi à chaque tour.[NEWLINE][NEWLINE]La [ICON_Faith] Foi s''obtient au fil du temps grâce à certains bâtiments, quartiers et doctrines. Appuyez sur F pour entendre votre réserve de Foi et votre Foi par tour.' WHERE Tag = 'LOC_META_128_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Votre ville a terminé la production du bâtiment Monument. Tous les bâtiments contribuent au développement d''une ville de manière spécifique. Le Monument augmente la [ICON_Culture] Culture générée par la ville, étendant son influence sur des cases supplémentaires. Amenez le curseur de navigation sur la case de la ville pour entendre ses bâtiments avec le résumé de la case, ou appuyez sur B à cet endroit pour lire ses bâtiments et d''autres détails géographiques.' WHERE Tag = 'LOC_META_40_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'La [ICON_Citizen] Population de votre première ville est passée de 1 à 2. Tant qu''une ville est bien nourrie et que ses habitants sont heureux, elle continue de croître. Les [ICON_Citizen] Citoyens de la ville exploitent les cases et les aménagements environnants, contribuant à de meilleurs rendements. Une [ICON_Citizen] Population plus élevée contribue à une recherche [ICON_Science] Science plus rapide, à une [ICON_Production] Production plus rapide de la ville et à une croissance [ICON_Culture] Culturelle plus rapide. La ville étant sélectionnée, appuyez sur Maj plus 6 pour entendre sa population, ses habitations et ses bâtiments.' WHERE Tag = 'LOC_META_125_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Rappel : les Bâtisseurs ne peuvent construire des aménagements qu''à l''intérieur des frontières de votre ville.[NEWLINE][NEWLINE]En générant de la [ICON_Culture] Culture, les frontières de votre ville s''étendront, vous donnant accès à davantage de ressources. La ville étant sélectionnée, appuyez sur Maj plus 4 pour entendre la progression de l''expansion de ses frontières.' WHERE Tag = 'LOC_META_38b_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Les unités à distance ont tendance à avoir une force défensive plus faible que les unités de mêlée ; gardez-les donc près d''unités alliées d''autres types pour les protéger. Une unité étant sélectionnée, appuyez sur Maj plus 6 pour entendre sa force de combat, sa force à distance ou de bombardement, et sa portée.' WHERE Tag = 'LOC_META_104_OTHER_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Le reste de ce tutoriel vous aidera à remporter votre première Victoire par domination.[NEWLINE][NEWLINE]Le but d''une Victoire par domination est que votre civilisation soit la dernière à occuper sa propre [ICON_Capital] Capitale.[NEWLINE][NEWLINE]Pour ce tutoriel, vous devez capturer la [ICON_Capital] Capitale de votre rival tout en l''empêchant de prendre la vôtre.[NEWLINE][NEWLINE]Trois objectifs facultatifs vous aideront à y parvenir. Appuyez sur Ctrl plus Maj plus T pour ouvrir la liste des objectifs du tutoriel. Les objectifs du tutoriel apparaissent aussi dans le panneau des notifications.' WHERE Tag = 'LOC_META_122_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Vous pouvez renoncer à un [ICON_GreatPerson] Personnage illustre dont vous ne voulez pas. D''autres joueurs peuvent alors le réclamer, la décision est irréversible, et vos [ICON_GreatPerson] Points de personnage illustre sont conservés pour une occasion future. Ciblez le personnage illustre et appuyez sur Suppr pour renoncer. Vous pouvez aussi appuyer sur Tab pour parcourir les boutons d''action disponibles de cette personne et sa biographie.' WHERE Tag = 'LOC_META_140_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Votre civilisation peut établir un nombre limité de [ICON_TradeRoute] Routes commerciales. Les quartiers Plateforme commerciale et Port peuvent augmenter cette capacité. Appuyez sur G pour entendre votre réserve et vos revenus d''Or ainsi que vos Routes commerciales actives et votre capacité de routes.' WHERE Tag = 'LOC_META_142_BODY' AND Language = 'fr_FR';
UPDATE LocalizedText SET Text = 'Au fil de la partie, réfléchissez à la façon de traiter avec vos voisins et observez-les attentivement pour comprendre leur stratégie. Appuyez sur F4 pour ouvrir la liste des dirigeants que vous avez rencontrés, puis appuyez sur Entrée sur un dirigeant pour ouvrir l''écran de Diplomatie détaillé le concernant.' WHERE Tag = 'LOC_META_157_BODY' AND Language = 'fr_FR';
